### ISSUE TITLE
The thread is blocked after libevent calls the bufferevent_write created by async.

### ISSUE THREAD

**Issue by TheDragonK** [libevent/libevent#1122] opened 2020-11-17 09:40 UTC
```
void *threadFn()
{
    string retStr = "woshoudaol$_S_H";
    bufferevent *dev = AI_Server::aiClientMap["123"];
    if (NULL != dev)
    {
        bufferevent_write(dev, retStr.c_str(), strlen(retStr.c_str()));
        printf("%s", "111");
    }
}

int test::sendMsg(bufferevent *dev)
{
    std::async(std::launch::async, threadFn);
    // std::thread task(threadFn);
    // task.detach();
}

**Comment by azat** [comment] 2020-11-17 20:17
bufferevent_write is async, it only adds data to the buffer, however it may have a lock (with BEV_OPT_THREADSAFE), which will be acquired in write code path.

From your lines of code it is hard to say, can you provide a reproducer?
Also can you attach with gdb to the program when it hang and attach stacktrace to this issue?

**Comment by azat** [comment] 2021-01-03 13:21
Closing, due to lack of reply, feel free to reopen

**Closed by azat** 2021-01-03 13:21 UTC
