### ISSUE TITLE
'+' is replaced with ' ' when it appears in url param value

### ISSUE THREAD

**Issue by okayabc** [libevent/libevent#1017] opened 2020-05-15 09:22 UTC
I have found a problem when an url param value contains '+', after call evhttp_find_header, the returned value is '+' is replaced with ' '  and others not changed.

**Comment by azat** [comment] 2020-05-15 09:39
I guess you are talking about the server.

Yes, this is the expected behavior (and this is not because you are calling `evhttp_find_header`), to fix new flag for parsing urls should be added, i.e. `EVHTTP_URI_DECODE_PLUS` or similar and also some API that will change default flags.

Is this a major issue for you? (this can be easily fixed in the user code)

**Comment by okayabc** [comment] 2020-05-15 09:51
Yes i talk about server. 
I haven't found EVHTTP_URI_DECODE_PLUS  in source code.
But evhttp_request_get_uri can print the url value with '+'.
I have replaced ' ' with '+' after calling evhttp_find_header to fix this problem.

**Closed** 2020-05-15 10:37 UTC
Labels: subsystem:http, type:feature

**Comment by okayabc** [comment] 2020-05-15 11:16
@azat , do you think the solution i mentioned in #1015 is reasonable and feasible? currently using this solution the service can run stably. The only difference is that i use one base thread and many work threads.

**Comment by okayabc** [comment] 2020-05-26 03:14
@azat , do  you think that replacing ' ' with '+' in url param is right? Is it possible that other character is also represented by ' ', so such replacement is not convinced。

**Comment by azat** [comment] 2020-05-26 09:23
>do you think that replacing ' ' with '+' in url param is right?

Yes, this is right, but should be [configurable](https://github.com/libevent/libevent/issues/1017#issuecomment-629138648)

> Is it possible that other character is also represented by ' ', so such replacement is not convinced。

No, this is only `+`

Take a look at `+` vs `%20` https://stackoverflow.com/a/2678602/328260
