### ISSUE TITLE
running 5000 connection in libevent leading to event_base_loop coming out

### ISSUE THREAD

**Issue by kushal4** [libevent/libevent#698] opened 2018-10-09 13:48 UTC
Hi,
I am running 5000 client in a different machine and i am running server which is using libevent in a different machine too. The server establishes 5000 connections without any error.
When the client program is terminated abnormally, the server program recieves  5000  event callbacks for the FIN packets sent by the abnormal closed client.After recieving 5000 callbacks,the event_base_loop() exits out without being in the infinite loop. Note that it exits normally (shows return code 0 in gdb).

But when i am running the server with the debug mode on for libevent,the server doesn't comes out of the event_base_loop() for the above situation undergone in the client program with 5000 clients.(running multiple number of times)

This happens mostly for >2000 connections (happens sometimes for 2200 connections, sometimes for 5000 connections, no apparent pattern).

I am using libevent for a server implementation, I can't have libevent exiting its event loop at any cost. 
I am expecting client to be launched again (when it crashes) and establish those connections again with the server. Hence Server need to keep running even if "all" of its sockets are closed. Listening socket is live though.

The interesting observation is that when client is establishing 2000 connections and crashing, all 2000 connections get successfully closed and event loop keeps running.

Why libevent exits its event loop for >2000 connection? How can I debug this? What message should I look for in the debug/verbose mode?

Using EV_LOOP_NO_EXIT_ON_EMPTY solved the issue. But I won't feel comfortable unless I know the reason of why it runs sometimes, and exits sometimes.

Appreciate any insight and help in root causing it.

**Comment by ploxiln** [comment] 2018-10-09 16:51
If the event for the listening socket receiving new connection is always enabled for libevent, then the event loop should not exit. Do you ever delete the event for the listening socket? Or do you set `EV_ET` (edge triggered)?

Can you share the exact libevent version and a minimal run-able code sample which can reproduce the problem?

**Comment by kushal4** [comment] 2018-10-10 14:56
Hi,
Thanks lot for your reply.
If I had a bug that accidentally deletes event for listening socket, then why the loop won't exit when run in debug mode? Note that in debug mode we are not using EV_LOOP_NO_EXIT_ON_EMPTY. However, I will check on it.

It will take us some time to create a minimal version that reproduces this issue.

One thought, what if the callback that is fired for each FIN is slow? When the client crashes, all 5000 FIN packet comes in a swarm and that many call back is fired. We have counted number of callbacks and it shows that callback has been fired for 5000 times. We are doing some bookkeeping actions before deleting event for the target socket and closing the socket itself. The book keeping routines take much longer time than the rate of incoming FIN packets. Hence I am speculating that there will be a buildup in the event queues inside libevent. Though eventually all 5000 connection get properly closed and events deleted for those connections, can the buildup cause any issue internal to libevent that is manifesting itself by exiting the loop?

When in debug mode, libevent prints huge number of debug message on screen, which should slow its loop performance. May be this debug message printing is slowing the rate of buildup? Can this be a possibility?

**Comment by azat** [comment] 2018-10-10 22:19
Here are my two cents.

> If I had a bug that accidentally deletes event for listening socket, then why the loop won't exit when run in debug mode?

So you are using evconnlistener, does your program has only one thread?

> One thought, what if the callback that is fired for each FIN is slow?

The callback execution time should not make any difference at all.

> We are doing some bookkeeping actions before deleting event for the target socket and closing the socket itself.

So if you are calling close() by yourself, maybe by some reason you are
closing the wrong fd? Can you verify this with "strace -k -eclose -f"
(or something else) that you do not close the listener socket? (if you
have at least one EBADF error you are likely has some kind of problem)

> When in debug mode, libevent prints huge number of debug message on screen, which should slow its loop performance. May be this debug message printing is slowing the rate of buildup? Can this be a possibility?

So this looks like you are talking about event_enable_debug_logging()
not about event_enable_debug_mode() (for me "debug mode" means this)
I would recommend you enable "debug mode" to catch some API misuse (with
event_enable_debug_mode() before any libevent API).
And if you are saying that it does not exit in "debug mode" can you
print currently monitored fds with event_base_dump_events() ?

Also please consider adding details (by your previous issues I would
list here at least next: environment, libevent version, threads, have
you tried some debug tools like valgrind and others, but the best you
can do is provide a buildable reproducer of course) into your issues at
creation time, not when somebody will ask for them (This will help us
and also other people who will have similar problems).

Regards,
Azat.

**Comment by azat** [comment] 2018-10-23 22:01
@kushal4 any news on this one?

**Closed** 2018-11-20 19:00 UTC

**Comment by azat** [comment] 2018-11-20 19:08
No answer, so closing.
