### ISSUE TITLE
Requirements for async DNS to work?

### ISSUE THREAD

**Issue by quanah** [libevent/libevent#1155] opened 2021-04-14 21:43 UTC
I found that when building libevent 2.12 in a chroot environment (using cowbuilder), the libevent test suite fails due to being unable to set up async name resolution.  This later impacts the software that links to libevent where that test suite also fails because it can't set up async name resolution.  Since this works outside of the chroot, I'm guessing I'm missing some set of files or packages there that are required, but not sure what.  /etc/resolv.conf exists, and if I install dig while in the chroot, I can do DNS lookups, so overall DNS seems functional.  Any tips appreciated.

**Comment by quanah** [comment] 2021-04-14 22:02
Test suite output:
```
Running tests:
EPOLL
Running tests:
SELECT
 test-eof:  test-eof: OKAY
 test-closed: OKAY
 test-closed: OKAY
 test-weof: [warn] event_base_new_with_config: no event mechanism available
OKAY
 test-weof: OKAY
 test-time: OKAY
 test-time: OKAY
 test-changelist: OKAY
 test-changelist: OKAY
 test-fdleak: OKAY
 test-dumpevents: OKAY (output not checked)
 regress: OKAY
 test-fdleak: OKAY
 test-dumpevents: OKAY (output not checked)
 regress: dns/initialize_nameservers:
  FAIL test/regress_dns.c:1020: assert(dns)
  [initialize_nameservers FAILED]
dns/initialize_nameservers:
  FAIL test/regress_dns.c:1020: assert(dns)
  [initialize_nameservers FAILED]
1/335 TESTS FAILED. (64 skipped)
FAILED
 regress_debug: 1/344 TESTS FAILED. (55 skipped)
FAILED
 regress_debug: dns/initialize_nameservers:
  FAIL test/regress_dns.c:1020: assert(dns)
  [initialize_nameservers FAILED]
dns/initialize_nameservers:
  FAIL test/regress_dns.c:1020: assert(dns)
  [initialize_nameservers FAILED]
1/335 TESTS FAILED. (64 skipped)
FAILED
make[4]: *** [Makefile:3109: test_runner_select] Error 1
make[4]: *** Waiting for unfinished jobs....
1/344 TESTS FAILED. (55 skipped)
FAILED
```

**Comment by quanah** [comment] 2021-04-14 22:40
Interestingly, if I enable a login shell trigger after the test fails, re-running the test suite with a TTY it passes no issue.

**Comment by mistotebe** [comment] 2021-04-15 09:06
This happens on systems that have an empty `/etc/resolv.conf`, like Debian package builds do. `EVDNS_BASE_INITIALIZE_NAMESERVERS` will set things up, return `res == 6` which is then treated as failure, same would probably happen if that file was missing. Shouldn't `EVDNS_BASE_INITIALIZE_NAMESERVERS` without `DNS_OPTION_NAMESERVERS_NO_DEFAULT` result in a success in such cases as a refinement to #569?

**Comment by mistotebe** [comment] 2021-04-15 09:15
Commit fc51bf2c5b686f623c9a2906ddad4042d5c3b39a is also of note here.

**Comment by quanah** [comment] 2021-04-15 15:50
Ah, i see, when I log in systemd populated resolv.conf.  Sigh

**Comment by azat** [comment] 2021-04-24 12:35
@quanah is this a problem? or we can close this?

We can skip this test if there is no `/etc/resolv.conf` (or similar on windows)
Maybe you want to address this?

**Comment by quanah** [comment] 2021-04-24 16:29
It doesn't just break the test, it breaks software using the library.

**Comment by ploxiln** [comment] 2021-04-24 18:23
What do programs and libraries using libc `gethostbyname()` or `getaddrinfo()` do if there is no `/etc/resolv.conf`? presumably they simply don't work either?

**Comment by azat** [comment] 2021-04-25 18:00
>It doesn't just break the test, it breaks software using the library.

programs can initialize the evdns w/o `/etc/resolv.conf` (using `DNS_OPTION_NAMESERVERS_NO_DEFAULT`/`EVDNS_BASE_NAMESERVERS_NO_DEFAULT`)

**Comment by azat** [comment] 2021-04-25 18:07
>What do programs and libraries using libc gethostbyname() or getaddrinfo() do if there is no /etc/resolv.conf? presumably they simply don't work either?

Good point, it also does not work:

```sh
$ docker run -v /dev/null:/etc/resolv.conf -v /tmp/getaddrinfo:/bin/getaddrinfo --rm -it debian:testing getaddrinfo
Type domain name:
libevent.org
getaddrinfo: Resource temporarily unavailable
```

*getaddrinfo example from this [gist](https://gist.githubusercontent.com/jirihnidek/bf7a2363e480491da72301b228b35d5d/raw/e9f7c43ad32ae490755129be463490db30854e1f/getaddrinfo_example.c)*

**Comment by azat** [comment] 2021-04-25 18:07
@quanah do you have any suggestions on how to handle this?

**Comment by mistotebe** [comment] 2021-04-25 21:30
I don't have too much of a preference what should happen, but it seems strange there is a default (to set `127.0.0.1:53` as the default nameserver) if it can never be used.

In a real world deployment, it makes sense to bail out in this case, the problem is if `EVDNS_BASE_INITIALIZE_NAMESERVERS` is meant to be useful, there needs to be a way for build/test environments to instantiate servers that rely on this in test environments like Debian's? If it means overriding the default location of `resolv.conf` that will be parsed by an environment variable, accepting the default (`127.0.0.1:53`) or just saying `/etc/resolv.conf` just **has to** have a valid `nameserver` item, that's up to the project?

**Comment by azat** [comment] 2021-04-26 21:16
For me `DNS_OPTION_NAMESERVERS_NO_DEFAULT` is enough.

Maybe introducing some env variable to configure evdns sounds like a good idea? (so that you can configure defaults for your environmen).

@mistotebe @ploxiln what do you think about this?

**Comment by mistotebe** [comment] 2021-04-27 06:38
You mean it should not fail in this case unless `DNS_OPTION_NAMESERVERS_NO_DEFAULT` is also specified? I'm good with that.

There's already a precedent for using `EVENT_*` in the environment to configure things, so potentially, don't know if it's better to let users specify resolv.conf location or go all the way and introduce a variable for nameservers, etc.

**Comment by azat** [comment] 2021-09-11 22:00
Ok, we already have `DNS_OPTION_NAMESERVERS_NO_DEFAULT`

And if you want to run tests in some clean env you should configure `/etc/resolv.conf` somehow.

**Closed by azat** 2021-09-11 22:00 UTC
Labels: tests, type:q

**Comment by mistotebe** [comment] 2021-09-13 08:25
What I meant was to allow the base to be set up (with a default of 127.0.0.1) **unless** `DNS_OPTION_NAMESERVERS_NO_DEFAULT` is passed so that isolated environments that know they don't need working DNS (like libevent's own tests on Debian CI) can actually start with the same binary that is used elsewhere.

**Comment by ploxiln** [comment] 2021-09-13 17:05
It looks like the one libevent test that is failing is `dns_initialize_nameservers_test()`, and the only thing this does is test that `/etc/resolv.conf` is loaded when you specify `EVDNS_BASE_INITIALIZE_NAMESERVERS`. So I think the correct "fix" is to just skip that test if `/etc/resolv.conf` is missing (or completely empty). (It usually shouldn't have permission to create that specific path to guarantee appropriate state for the test, and there isn't really any other functionality the test is needed for.)

**Comment by mistotebe** [comment] 2021-09-13 21:44
Yes, there's also other software (OpenLDAP in my case) that depends on libevent's evdns and for us it's proven quite hard to document what you need your host to look like just to pass the test suite. That's why this ticket exists, either we need to be able to load a resolv.conf file/settings provided by the environment (a more general solution) or at least provide "a default" so that an evdns_base can be set up.

**Comment by ploxiln** [comment] 2021-09-14 05:50
evdns does provide mechanisms for such a default, the other program's test setup would just have to be modified to use them.

If the program calls `evdns_base_new(event_base, EVDNS_BASE_INITIALIZE_NAMESERVERS)`, it fails if `/etc/resolv.conf` is missing, it doesn't get defaults.

If the program instead does `dns_base = evdns_base_new(event_base, 0)` and then either:
  * `evdns_base_nameserver_ip_add(dns_base, "127.0.0.1");` or
  * `evdns_base_resolv_conf_parse(dns_base, DNS_OPTION_NAMESERVERS|DNS_OPTION_HOSTSFILE, "/etc/resolv.conf")` and _ignore the error return value_ (this will fill in default "127.0.0.1" if reading the file fails)

then it will effectively get defaults that may be sufficient for tests in a container without `resolv.conf`

**Comment by mistotebe** [comment] 2021-09-14 07:39
Thanks @ploxiln, that looks doable, I'll see if I can adapt our code accordingly.

**Comment by asheplyakov** [comment] 2023-05-19 10:43
> evdns does provide mechanisms for such a default, the other program's test setup would just have to be modified to use them.
> 
> If the program calls `evdns_base_new(event_base, EVDNS_BASE_INITIALIZE_NAMESERVERS)`, it fails if `/etc/resolv.conf` is missing, it doesn't get defaults.
> 
> If the program instead does `dns_base = evdns_base_new(event_base, 0)` and then either:
> 
>     * `evdns_base_nameserver_ip_add(dns_base, "127.0.0.1");` or
> 
>     * `evdns_base_resolv_conf_parse(dns_base, DNS_OPTION_NAMESERVERS|DNS_OPTION_HOSTSFILE, "/etc/resolv.conf")` and _ignore the error return value_ (this will fill in default "127.0.0.1" if reading the file fails)
> 
> then it will effectively get defaults that may be sufficient for tests in a container without `resolv.conf`

In a production environment one wants a program (for instance slapd from openldap) to fail if /etc/resolv.conf is missing or broken.
And the very same binary should work and ignore missing/empty/broken /etc/resolv.conf in a test environment (building separate versions for tests and production kind of denies the purpose of testing).

Hence people are asking for some kind of "tests/production" knob (environment variable, config file, whatever), which works **without** rebuilding the binary being tested.
