### ISSUE TITLE
Link error on Win32 (VS2017)

### ISSUE THREAD

**Issue by Code7R** [libevent/libevent#691] opened 2018-09-14 19:56 UTC
I tried to build todays libevent (master) on Windows with Visual Studio 2017 and no luck there. Static libraries seem to build but linking fails due to some unresolved symbol, either for all executables (when building with MSVS built-in cmake) or just for some (when built with msbuild, i.e. following README instructions).

See attachments.

[bad_build.txt](https://github.com/libevent/libevent/files/2384700/bad_build.txt)
[bad_build_msbuild.txt](https://github.com/libevent/libevent/files/2384701/bad_build_msbuild.txt)

**Comment by azat** [comment] 2018-10-27 17:17
@Code7R thanks fore the report and the logs, I will take a look at them once I will have time to fix the root case -- #702  
So let's close this in favor to the linked issue.

**Closed by azat** 2018-10-27 17:17 UTC
Labels: os:win32

**Comment by azat** [comment] 2018-10-28 16:56
> bad_build.txt

This fails because of `event_debug_logging_mask_` it has been fixed in fb866645, could you confirm?

> bad_build_msbuild.txt

This one looks like some depedency problem, since event_extra.lib is used before it is created, i.e. message about creating:
> 12>   Creating library C:/Work/git/libevent/build/lib/Debug/event_extra.lib

goes after message about using:
> 17>LINK : fatal error LNK1104: cannot open file 'lib\Debug\event_extra.lib'

**Comment by azat** [comment] 2018-10-28 17:01
Looking into cmake rules again and I can confirm that samples has required libraries as dependencies, so can you:
- verify with at least fb86664 (see previous commit)
- do you run some kind of parallel build? could you try run sequential?
- could you try clean build?

**Comment by azat** [comment] 2018-11-21 07:17
> do you run some kind of parallel build? could you try run sequential?

Indeed, looks like there are some problems with parallel builds under msbuild (ugh), next patch should fix it -- f99079cd19bdd8e5a32c9510348d2780233e2f37 (but I'm still digging into the root cause).

**Comment by azat** [comment] 2018-11-22 17:39
And it looks like msbuild (or whatever stuff is used there) does not like when shared/static libraries has the same name, IOW reverting this part (3842291534ec7f184e9e90d562377873b2128336) fixes the [build](https://ci.appveyor.com/project/azat/libevent/build/job/ca9k3c76amc4qr76)
