### ISSUE TITLE
ETA for next release?

### ISSUE THREAD

**Issue by wongsyrone** [libevent/libevent#711] opened 2018-11-12 01:24 UTC
According to github statistics, it's ` 250 commits to master since this release`. Any ETA to release the next version? It seems lots of bugfixes there.

**Comment by azat** [comment] 2018-11-12 04:37
Hi!

I don't have any ETAs but I was going to make it soon.
Right now I'm fixing some other major bugs that I want to include into release.

**Comment by azat** [comment] 2018-11-13 20:01
So I'm closing this, since this will not help in making the release.

But if you ask "how can I help?" then the answer will be:
- go through issues/patches and mark/comment which of them should be backported
- report which patches you are interested in from upstream
- run regression tests (see https://github.com/libevent/libevent-extras)

**Closed by azat** 2018-11-13 20:01 UTC
