### ISSUE TITLE
httpsclient test failed, socket error = Invalid argument (22)

### ISSUE THREAD

**Issue by lkunxyz** [libevent/libevent#1275] opened 2022-05-09 02:41 UTC
![image](https://user-images.githubusercontent.com/3108757/167329758-213b3d97-5cbd-4c8a-9357-c343718bf624.png)

libevent version: libevent-2.1.11-stable
use ipv6 

i got a error :
some request failed - no idea which one though!
socket error = Invalid argument (22)

use google-chrome browser access this url [https://[fc00:1913::e9a9:aaf5:710:8dd1]/UniSSO/auth/getUserSessionInfo.json?sessionid=ad47-8831a89fd7105dbbdc4](url)  is not any problem

Can anybody help me?
thanks

**Comment by azat** [comment] 2022-05-12 12:39
@lkunxyz hi!

The problem is that address with square brackets passed to getaddrinfo, should be fixed in the referenced patch.

**Closed** 2022-05-12 12:38 UTC
