### ISSUE TITLE
bufferevent+openssl will crash on iOS / macOS

### ISSUE THREAD

**Issue by kenpingliu** [libevent/libevent#378] opened 2016-07-14 09:52 UTC
Versions 2.0.2x ~ 2.1.x and the master all have this issue.

I fund this issue while use bufferevent_openssl_socket_new() to connect a validated host and its invalidated port, like as 127.0.0.1:344.
But if I use bufferevent_socket_connect_hostname() at first, and then use bufferevent_openssl_filter_new() after TCP connected sucessful, It will work fine.

After debug with source code, fund the crash source at do_handshake() @ bufferevent_openssl.c

```
case BUFFEREVENT_SSL_CONNECTING:
case BUFFEREVENT_SSL_ACCEPTING:
    // Here, connection has an ECONNREFUSED error for 127.0.0.1:344, cann't continue to handshake
    // Mine solution:
    //  int optval = 0;
    //  socklen_t optlen = sizeof(optval);
    //  int fd = SSL_get_fd(bev_ssl->ssl);
    //  getsockopt(fd, SOL_SOCKET, SO_ERROR,(char*) &optval, &optlen);
    //  if (optval==ECONNREFUSED) { conn_closed(bev_ssl, BEV_EVENT_READING, optval, r); return -1; }

    ERR_clear_error();
    r = SSL_do_handshake(bev_ssl->ssl);
```

Sorry my poor English.
Can you fix it?
thanks all

**Comment by azat** [comment] 2016-07-14 10:07
@kenpingliu thanks for the report! I will take a look. Also if you have time can you add a unit test for this particular case? (`test/regress_ssl.c`)

**Comment by kenpingliu** [comment] 2016-07-15 02:53
@azat  thanks for your replying, here is my code.
this code can work fine on Android/Windows/Linux, it will output
`test_ev_bevcb[0x1edfba0] 20(01RD|02WR|10EF|20ER|80CN)`
But not on iOS/macOS, it will directly exit while i connect to 127.0.0.1:344, And if i debug my program in Xcode, Xcode could display a crash stack.

I needs bufferevent_openssl_socket_new() because of watermark. I fund the watermark can work fine for bufferevent_openssl_socket_new() but not bufferevent_socket_new()+bufferevent_openssl_filter_new()
<img width="894" alt="xcode_crash" src="https://cloud.githubusercontent.com/assets/4023594/16862164/14cab9d8-4a7a-11e6-8084-3632e3ab7699.png">

[test_code.zip](https://github.com/libevent/libevent/files/365095/test_code.zip)

**Comment by azat** [comment] 2016-07-20 16:05
@kenpingliu can you try not to link this binary with `ssl`/`crypto` libs manually, just `libevent_openssl`?

**Comment by kenpingliu** [comment] 2016-07-21 07:22
@azat if I just link with libevent_openssl like as follows
`g++ test_evconn.cpp -I ./inc lib/macos_x86_64/libevent.x86_64.a lib/macos_x86_64/libevent_openssl.x86_64.a lib/macos_x86_64/libevent_pthreads.x86_64.a -lpthread -o tev`
It will fail with many errors, like as:
`"_BIO_clear_flags", referenced from:
      _bio_bufferevent_write in libevent_openssl.x86_64.a(bufferevent_openssl.o)
      _bio_bufferevent_read in libevent_openssl.x86_64.a(bufferevent_openssl.o)
...`

**Comment by kenpingliu** [comment] 2016-07-21 07:44
@azat thanks for all, I fund a problem, if i add the code 
`signal(SIGPIPE, SIG_IGN);`
before call any libevent function. It will work fine.
But can not work in iOS/macOS Xcode project, when i add this code in main() function for main.m, the app will crash too.

**Comment by azat** [comment] 2016-07-25 17:15
Thanks for the info (didn't noticed this before, because github doesn't send emails on updates/edits)! I will take a look. BTW which version of osx do you have?

**Comment by azat** [comment] 2016-07-25 17:18
Also according to that link `You can handle this in **one of two** ways` so I'm still confused about this, do you have multi-threaded app?

**Comment by kenpingliu** [comment] 2016-07-26 01:44
My OSX version is 10.11.6 (15G31), And this issue exists under iOS also, but not Android/Linux/Windows. It occurs in only Apple's OS.
Yeah, My app is a multi-threaded app, and the same code will be compiled and port for run in Android/iOS/Linux/macOS/Windows.

**Comment by azat** [comment] 2016-07-26 07:07
Can you try to reproduce this in single-thread/thread-less?

**Comment by kenpingliu** [comment] 2016-07-27 04:04
Hi @azat, here is my test code.
1. use 'brew install libevent openssl'
It will install livevent 2.0.22 and openssl 1.0.2h
2. compile with: g++ test_evconn.cpp -I ./inc -lssl -lcrypto -levent -levent_openssl -levent_pthreads -lpthread -o tev
3. run with gdb: sodu gdb tev

(gdb) r
Starting program: /Users/kenping/Downloads/libeventopenssl/test/tev 
test_ev_ssl_connect 127.0.0.1:344, single_step=1
setsockopt SO_NOSIGPIPE failed: [22]Invalid argument
test_ev_ssl_connect OK, wait for event callback

Program received signal SIGPIPE, Broken pipe.
0x00007fff89ded91a in write () from /usr/lib/system/libsystem_kernel.dylib
(gdb)

we can find that process receive a SIGPIPE signal.
So if i remove the code "signal(SIGPIPE, SIG_IGN);", the process will exit after this signal while not be loaded by gdb (because of gdb will help to ignore this signal??).
[test_evconn.cpp.zip](https://github.com/libevent/libevent/files/385254/test_evconn.cpp.zip)

**Comment by azat** [comment] 2016-08-04 09:15
> Hi @azat, here is my test code.

Hi @kenping, thanks for the effort!

Actually event_use_pthreads() does not create any threads, it just
installs appropriate callbacks for locks/conds, to make it's structures
thread-safe (against user threads), so I guess that you had
single-threaded app before too (of course if you not omit some part of
sources).

> 1. use 'brew install libevent openssl'
> It will install livevent 2.0.22 and openssl 1.0.2h

It is better to test latest libevent, but of course this shouldn't
change anything for this particular issue.

> 2. compile with: g++ test_evconn.cpp -I ./inc -lssl -lcrypto -levent -levent_openssl -levent_pthreads -lpthread -o tev
> 3. run with gdb: sodu gdb tev
> 
> (gdb) r
> Starting program: /Users/kenping/Downloads/libeventopenssl/test/tev 
> test_ev_ssl_connect 127.0.0.1:344, single_step=1
> setsockopt SO_NOSIGPIPE failed: [22]Invalid argument
> test_ev_ssl_connect OK, wait for event callback
> 
> Program received signal SIGPIPE, Broken pipe.
> 0x00007fff89ded91a in write () from /usr/lib/system/libsystem_kernel.dylib
> (gdb)
> 
> we can find that process receive a SIGPIPE signal.
> So if i remove the code "signal(SIGPIPE, SIG_IGN);", the process will exit after this signal while not be loaded by gdb (because of gdb will help to ignore this signal??).

Yeah, gdb will break on SIGPIPE anyway, so it is not good to test
program under gdb with it's default.
  (gdb) info signals SIGPIPE
  Signal        Stop      Print   Pass to program Description
  SIGPIPE       Yes       Yes     Yes             Broken pipe

But you can change this behaviour:
  (gdb) handle SIGPIPE nostop

So, the question is, can you reproduce this without gdb?

> [test_evconn.cpp.zip](https://github.com/libevent/libevent/files/385254/test_evconn.cpp.zip)

**Comment by azat** [comment] 2016-10-03 00:01
@kenpingliu so everything good with *2.1.6*?

**Comment by kenpingliu** [comment] 2016-10-08 06:06
@azat sorry for the later response. The issue exists in 2.1.6 beta also. If i remove the following codes, the applications will crash also.
`
#	if defined(SO_NOSIGPIPE) && !defined(MSG_NOSIGNAL)
    	// Ignore SIGPIPE for every connection
    	int value = 1;
    	evutil_socket_t fd = bufferevent_getfd(bev);
    	if ( fd>0 && setsockopt(fd, SOL_SOCKET, SO_NOSIGPIPE, &value, sizeof(value))==-1 )
    	{
    		printf("setsockopt SO_NOSIGPIPE failed: [%d]%s\n", errno, strerror(errno));
    	}
#	endif
`

**Comment by kenpingliu** [comment] 2016-12-22 05:15
My final codes to avoid this issue
`#if defined(SO_NOSIGPIPE)
    evutil_socket_t fd = bufferevent_getfd(bev);
    if ( fd<1 && (fd=socket(AF_INET, SOCK_STREAM, IPPROTO_TCP))>0 )
    {
        bufferevent_setfd(bev, fd);
    }
    int option = 1;
    if ( fd>0 && -1==setsockopt(fd, SOL_SOCKET, SO_NOSIGPIPE, (const void *)&option, sizeof(option)) )
    {
        // Log error
    }
#endif
    
    if ( 0!=bufferevent_socket_connect(bev, sa, salen) )
    {
        // log error
    }`

**Comment by NathanFrench** [comment] 2019-02-07 17:44
Unfortunately, you will not be able to avoid those SSL pipe errors by doing that `setsockopt` *AFTER* you connect. Try plopping that right after `bufferevent_openssl_socket_new`.

**Comment by NathanFrench** [comment] 2019-02-07 18:18
> My final codes to avoid this issue, call setsockopt() before bufferevent_socket_connect():
> 


This is the proper fix. Closing the issue.

**Closed by NathanFrench** 2019-02-07 18:18 UTC
Labels: os:osx
