### ISSUE TITLE
Lost http request if bufferevent_writecb is called before evhttp_connection_connect_ is done

### ISSUE THREAD

**Issue by nritsche** [libevent/libevent#733] opened 2018-12-11 00:44 UTC
I am using libevent 2.1.8 for an HTTP client and found that some times requests go missing. The callback passed to `evhttp_make_request` will just never get called.
I tracked it down to `bufferevent_writecb` getting called with event `WRITE_EV`, after `evhttp_connection_connect_` called `evhttp_connection_reset_`, but before it calls `bufferevent_socket_connect`.
`bufferevent_writecb` will therefor delete the bufferevent, because `bufev_p->connecting == 0` and `evbuffer_get_length(bufev->output) == 0` (it didn't get copied from the request buffer yet).

I was able to make it work by locking the bufferevent in `evhttp_connection_connect_`::`2532-2581`.

The problem does not occur with the latest version from `master` but I can't tell if it has been fixed or just coincidentally doesn't happen (this problem obviously depends on timing).

**Comment by azat** [comment] 2018-12-12 08:34
>I tracked it down to bufferevent_writecb getting called with event WRITE_EV, after evhttp_connection_connect_

It should not, since later installs writecb to NULL.

>called evhttp_connection_reset_, but before it calls bufferevent_socket_connect.

Hm, this should break anything if you do not misuse http API, can you post minimal reproducer?

>I was able to make it work by locking the bufferevent

Are you trying to manipulate one evcon from multiple threads?
Does you event_base loops in the same thread as the one that creates/schedules connections/requests?

>The problem does not occur with the latest version from master but I can't tell if it has been fixed or just coincidentally doesn't happen (this obviously depends on timing).

Can you bisect?

**Comment by nritsche** [comment] 2018-12-18 01:52
> Are you trying to manipulate one evcon from multiple threads?
No, I am creating a new evcon in every thread, using the same `event_base`. I am then passing the evcon to the callback function of the request, where it gets free'd.

> Does you event_base loops in the same thread as the one that creates/schedules connections/requests?
No.

> Can you bisect?
I have to correct myself. I also see the problem with the latest version from `master`.

**Comment by nritsche** [comment] 2018-12-19 00:11
> Hm, this should break anything if you do not misuse http API, can you post minimal reproducer?

For now I can only point you [here](https://github.com/kotekan/kotekan/blob/master/tests/boost/test_dataset_manager_rest.cpp).

**Comment by azat** [comment] 2018-12-23 15:02
>I tracked it down to bufferevent_writecb getting called with event WRITE_EV, after evhttp_connection_connect_ called evhttp_connection_reset_, but before it calls bufferevent_socket_connect.

Can you post stacktrace for `bufferevent_writecb()` in this case?

> bufferevent_writecb will therefor delete the bufferevent

I guess you mean disable `EV_WRITE`?

>For now I can only point you here (This is the client implementation).

It passes in my env, or I missing some flag?:

```shell
root@a18516c7a6a7:/src/kotekan/.cmake# ../tests/test_dataset_manager_rest
Registering file type: raw
Registering file type: ring
Running 1 test case...
restServer: Adding REST endpoint: /endpoints
restServer: Adding REST endpoint: /register-state
restServer: Adding REST endpoint: /send-state
restServer: Adding REST endpoint: /register-dataset
restServer: started server on address:port 127.0.0.1:12048
restClient: libevent version: 2.2.0-alpha-dev
                  10inputState : 0x0
                  10inputState : 0x5bb406e812693299

1420611164545393871 - [[1,"1"],[2,"2"],[3,"3"]]
1420611164545393871 - 0
1420611164545393871 - 6607914147070423705

*** No errors detected
```

**Comment by azat** [comment] 2018-12-23 15:07
>It passes in my env, or I missing some flag?:

But not with latest upstream, /me digging

**Comment by azat** [comment] 2019-01-10 19:03
Can you please try libevent with the referenced patch, or simply build it from my fork:
```
  https://github.com/azat/libevent be-sock-connect-mt
```

And you need to modify you client and add `BEV_OPT_THREADSAFE` to the bufferevent that is used for http layer, here is an [example patch](https://gist.github.com/azat/b5fa155101312cab8f399239458facfa)

**Comment by azat** [comment] 2019-01-10 19:16
*Last patch from the `be-sock-connect-mt` had been dropped*

**Comment by nritsche** [comment] 2019-01-10 23:31
> Can you please try libevent with the referenced patch, or simply build it from my fork:
> 
> ```
>   https://github.com/azat/libevent be-sock-connect-mt
> ```
> And you need to modify you client and add `BEV_OPT_THREADSAFE` to the bufferevent that is used for http layer, here is an [example patch](https://gist.github.com/azat/b5fa155101312cab8f399239458facfa)
> 
> _(P.S. my patch contains some debug stuff too, just ignore those bits)_

This does fix the problem for me.
Thanks @azat !
Can you explain why having the event loop in a different thread than the request is bad design and how it should be done otherwise?

**Comment by ploxiln** [comment] 2019-01-11 01:52
Threads and event loops are sort of opposite ways of doing things. Some applications just use threads for everything that runs concurrently, some applications use an event loop and never spawn any threads (beyond the original/implicit process "thread").

You can use an event loop to do a bunch of things in a thread, while there are also other threads, but the best way is for that event loop and its structures to not have any interaction with those other threads directly, but only through messages passed through pipes (which the event loop can asynchronously receive and process). You could also implement queues with mutexes, and wait for notification of items via a pipe, or you can often safely schedule a simple callback to run in an event loop on another thread. The event loop is, more or less, originally designed and optimized to run all in a single thread.

libevent goes pretty far to add thread-safety to an event loop, and I find azat's investigation of the complex issues that come up rather impressive. Some other event loop libraries just say "no, don't directly touch the event loop from another thread". For example the python library tornado has [IOLoop.add_callback](http://www.tornadoweb.org/en/stable/ioloop.html#tornado.ioloop.IOLoop.add_callback) which says

> Note that this is the only method in IOLoop that makes this thread-safety guarantee; all other interaction with the IOLoop must be done from that IOLoop’s thread. add_callback() may be used to transfer control from other threads to the IOLoop’s thread.

and there are often issues opened up with strange bugs, that turn out to be caused by use of threads. You absolutely can use threads with event loops (multiple!), but that is an advanced topic. The basic model is an event loop living entirely self-contained within one thread (so one thread can do multiple concurrent things).

**Comment by azat** [comment] 2019-01-11 07:14
Great explanation by @ploxiln 
Just few notes below

> You could also implement queues with mutexes, and wait for notification of items via a pipe

event loop allows you to avoid locking (it is not always possible of course, but this idea should be kept in mind during development to avoid extensive locks usage). And if you need to pass data between threads, you can do this via pipes/...

That said that if you have application with multiple threads, one event loop and hence a lot of syncing primitives, later can be avoided by creating event loop per thread and balance events between event loops (of course if you do not have some global context or something similar).

**Comment by azat** [comment] 2019-01-11 07:15
> This does fix the problem for me.

Great, I will take a look at the patch one more time (I think that there can be some caveats) and after merge it into upstream.

**Comment by azat** [comment] 2019-01-11 17:22
> I think that there can be some caveats

And not only caveats...
So after looking this it again I don't see a lot of sense in it, and here is my explanation.

After this patch `eventcb` still will be called in parallel, and this means that `evhttp_connection_cb()` will be called in parallel with `evhttp_make_request()` this is ~safe~ racy now, and keeping this always in mind is complicated (or/and requires locking for `evhttp_connection` at least).

We could use `bufferevent`'s `lock` in theory (in `evhttp_make_request()`), but every call to `evhttp_connection_*()`/`evhttp_request_*()` from the different thread will be racy and that's why I don't see sense in "fixing" it.

Also note, that this is not a problem for `writecb/evhttp_write_cb`/`readcb/evhttp_read_cb` (with `BEV_OPT_THREADSAFE`), because each callback is runned under bufferevent lock.

As for your client, you have two options:
- **rewrite your client to run event loop and request scheduling in the same thread** (by passing requests via pipe/`bufferevent_pair` or something else), this is **preferable choice** (will make code cleaner)
- *or use some quirks like, `event_base_once()` to run `::make_request` from the thread of event loop*, this will work, but if http requests is what you application does a lot I would strongly recommend first option.

After all above I'm going to close the issues, fill free to reopen if you have strong objections.

**Closed by azat** 2019-01-11 17:22 UTC
Labels: subsystem:http

**Comment by nritsche** [comment] 2019-10-29 18:06
> As for your client, you have two options:
> 
>     * **rewrite your client to run event loop and request scheduling in the same thread** (by passing requests via pipe/`bufferevent_pair` or something else), this is **preferable choice** (will make code cleaner)

Thanks @azat for the recommendations. I am trying to implement your suggestion, but it's not working and I'm not sure if I am doing it right. Can you please point me at an example?

**Comment by azat** [comment] 2019-10-29 21:28
>but it's not working and I'm not sure if I am doing it right

So everything works after `bufferevent_flush()`?

>Is there a FLAG I have to set somewhere for the bufferpair to always flush everything through?

It should have any buffering, maybe you enable some watermarks? can you share the code?

**Comment by nritsche** [comment] 2019-10-29 21:43
I could get around manually flushing. It was the same issue as this: https://github.com/libevent/libevent/issues/642

**Comment by azat** [comment] 2019-10-29 21:50
>It should have any buffering, maybe you enable some watermarks? can you share the code?

Sorry, type `s/should/shouldn't`, so bufferevent do not have any buffering, unless watermark is enabled.

>It was the same issue as this

That issue is about

>The read callback in the client code was written to process only one message at time from the server as the server code sends two messages separately at different times (but pretty close to each other in time) for each request it receives from the client.

So the read callback was the root cause.
If you have the same, then I'm suggesting you to simply fix it.
If no, please share the reproducer, or at least some details

**Comment by nritsche** [comment] 2019-10-30 00:14
Thanks a lot @azat .
The fix after your suggestions is in https://github.com/kotekan/kotekan/commit/60ac1992bb4179866e41d6943666be14848ae1f1
