### ISSUE TITLE
undefined reference when building with LLVM/clang

### ISSUE THREAD

**Issue by tpgxyz** [libevent/libevent#827] opened 2019-06-05 09:52 UTC
Lots of undefined reference errors when compiling with LLVM/clang
Full build log can be found here http://file-store.openmandriva.org/api/v1/file_stores/06ec640360390e7ddd8d70fe979ff81ff98b9f16.log?show=true

```
make[1]: Leaving directory '/builddir/build/BUILD/libevent-2.1.10-stable'
BUILDSTDERR: bufferevent_openssl.c:975: error: undefined reference to 'event_initialized'
BUILDSTDERR: bufferevent_openssl.c:976: error: undefined reference to 'event_get_fd'
```

```
make[1]: Leaving directory '/builddir/build/BUILD/libevent-2.1.10-stable'
BUILDSTDERR: evthread_pthread.c:187: error: undefined reference to 'evthread_set_lock_callbacks'
BUILDSTDERR: evthread_pthread.c:188: error: undefined reference to 'evthread_set_condition_callbacks'
```

```
make[1]: Leaving directory '/builddir/build/BUILD/libevent-2.1.10-stable'
BUILDSTDERR: /tmp/lto-llvm-11948b.o:ld-temp.o:function evdns_add_server_port_with_base: error: undefined reference to 'event_mm_malloc_'
BUILDSTDERR: /tmp/lto-llvm-11948b.o:ld-temp.o:function evdns_add_server_port_with_base: error: undefined reference to 'event_assign'
```

**Comment by azat** [comment] 2019-06-05 22:25
The problem is not in clang but in `-Wl,--no-undefined` in your `LDFLAGS`

And the only way to fix this is to link libevent.so during linking libevent_openssl.so, and I don't think that this should be done.

So you have two options:
- either remove `-Wl,--no-undefined` completely
- or use `-Wl,--unresolved-symbols=ignore-in-object-files` (i.e. `-Wl,--no-undefined -Wl,--unresolved-symbols=ignore-in-object-files'`), but this will break some function existence check, hence only first is your option

Frankly speaking I do not understand why do you have it (but I guess that this is some kind of automation), since defaults are pretty sane (man ld):

           The default behaviour is to report errors for any undefined symbols referenced in shared libraries if the linker is being used to create an executable, but to allow them if the linker is
           being used to create a shared library.

*P.S. and I pretty sure that libevent is not the only project that will have problems*

**Comment by tpgxyz** [comment] 2019-06-06 11:15
I've fixed it differently
https://github.com/OpenMandrivaAssociation/libevent/blob/master/libevent-2.1.10-stable-fix-linking.patch

**Comment by azat** [comment] 2019-06-13 18:38
You just link every library with libevent_core, so just like I already wrote:

> And the only way to fix this is to link libevent.so during linking libevent_openssl.so, and I don't think that this should be done.

Closing, feel free to reopen if you still disagree.

**Closed by azat** 2019-06-13 18:38 UTC
Labels: status:unconfirmed
