### ISSUE TITLE
Phantom event callbacks with EV_ET

### ISSUE THREAD

**Issue by htuch** [libevent/libevent#984] opened 2020-03-26 19:13 UTC
In Envoy today, we sometimes have network socket FDs setup with `event_assign` to watch for `EV_CLOSED | EV_ET | EV_PERSIST`. The callback function is invoked on `EV_READ` or `EV_WRITE` however, as a result of the following call chain:

1. `epoll_dispatch` issuing read/write events with `EV_ET` set, see https://github.com/libevent/libevent/blob/0d2f170048a4da1fd7beb553455e1679122a3833/epoll.c#L504.

2. `evmap_io_active` masking out `EV_READ` and `EV_WRITE` (since we're only looking for `EV_CLOSED`) but preserving `EV_ET` in https://github.com/libevent/libevent/blob/0d2f170048a4da1fd7beb553455e1679122a3833/evmap.c#L436.

3. `event_active_nolock_` delivering an event to the callback with `res` set to `EV_ET`, despite no registered event actually firing.

This can be fixed with the following patch:
```
diff --git a/evmap.c b/evmap.c
index ffc991f5..d824c062 100644
--- a/evmap.c
+++ b/evmap.c
@@ -432,7 +432,7 @@ evmap_io_active_(struct event_base *base, evutil_socket_t fd, short events)
        if (NULL == ctx)
                return;
        LIST_FOREACH(ev, &ctx->events, ev_io_next) {
-               if (ev->ev_events & events)
+               if (ev->ev_events & (events & (EV_READ | EV_WRITE | EV_CLOSED)))
                        event_active_nolock_(ev, ev->ev_events & events, 1);
        }
 }
```

I'm wondering if folks agree that this is a bug and whether the above patch is the correct fix?

CC @asraa @adisuissa

**Comment by azat** [comment] 2020-03-26 23:01
But then you will miss the close event, no? (FWIW if you will provide a 50L reproducer that will helps in understanding what you are trying to solve, looks that it is pretty simple to write such)

**Comment by htuch** [comment] 2020-03-26 23:35
@azat the above patch explicitly allows for `EV_CLOSED` in the whitelist of events that we mask in. I can work on a reproducer, sure.

**Comment by htuch** [comment] 2020-03-31 15:21
@azat see https://github.com/htuch/envoy/commit/40b8ab87b0c65768e045467a645f433061246fb1 for a minimal reproducer. You can see here that we're subscribed only for `EV_CLOSED` events, but an injected `EV_READ` triggers the callback.

**Comment by azat** [comment] 2020-04-05 16:03
>event_active_nolock_ delivering an event to the callback with res set to EV_ET despite no registered event actually firing.

But you are calling `event_active()` which makes an event active **manually** (so not sure how this is related to the evmap and epoll code), and it will make it active regardless it was registered with this events or not

P.S. your patch will break real `EV_CLOSED` handling

**Comment by htuch** [comment] 2020-04-05 23:23
I'll work on an FD-triggered example. Can you explain how this breaks real `EV_CLOSED` handling? AFAICT, I'm just masking READ/WRITE/CLOSED events _in_ for consideration, and ignoring other things like `EV_ET`.

**Comment by azat** [comment] 2020-04-06 09:55
Indeed, but EV_CLOSED will be delivered with EV_READ|EV_WRITE (i.e. EOF) instead, which will be filtered out before and the callback will never be triggered and you will got endless loop - [repro](https://gist.github.com/azat/797db20e950960e421e5bdc44d407eb1).

**Comment by htuch** [comment] 2020-04-06 15:48
@azat I've updated my repro at https://github.com/htuch/envoy/commit/5b5da87514e1bc57c56c523f3ef34122706cba0a, using `pipe` instead of `event_activate`.

What I think is going on is that when we get remote hang-up/close, epoll is seeing `EPOLLERR` or `EPOLLHUP`. It then sets the events as `EV_READ | EV_WRITE` in https://github.com/libevent/libevent/blob/dd02ad9544ec857412e8a5a0462ddcb29e8045f6/epoll.c#L491. Then, steps (2) and (3) at the top-level comment happen.

What I think is going on is two things:
1. libevent is generating a callback for remote close, whose events get masked down to empty, when we are subscribed to `EV_CLOSED`. This seems wrong; either a callback shouldn't happen or `EV_CLOSED` should be set.
2. Envoy should be monitoring for `EV_CLOSED | EV_READ | EV_WRITE` to detect remote close. Is this specified anywhere? What's the correct way to handle all possible close scenarios?

**Comment by azat** [comment] 2020-04-07 10:04
>I've updated my repro at htuch/envoy@5b5da87, using pipe instead of event_activate.

Thanks, but my example already has everythin (AFAIU)

>libevent is generating a callback for remote close, whose events get masked down to empty (well, EV_ET, which is effectively empty), when we are subscribed to EV_CLOSED. This seems wrong; either a callback shouldn't happen or EV_CLOSED should be set.

Indeed, this is exactly what is happens

>Envoy should be monitoring for EV_CLOSED | EV_READ | EV_WRITE to detect remote close. Is this specified anywhere? What's the correct way to handle all possible close scenarios?

But why are you bothers about the events, can you just use separate callback for the `EV_CLOSED` event?

P.S. 

>What I think is going on is that when we get remote hang-up/close, epoll is seeing EPOLLERR or EPOLLHUP. It then sets the events as EV_READ | EV_WRITE in

actually the `close` will produce `EPOLLHUP` on the other side and this behaviour, but `shutdown(SHUT_WR)` will produce `EPOLLRDHUP` and will call the callback with `EV_CLOSED|...`

**Comment by htuch** [comment] 2020-04-07 13:29
I guess this boils down to the following question:

* Should libevent ever generate a callback for an event which `event_assign` has not subscribed?

In this example, we subscribe to `EV_CLOSED`, but we get an event that is not in this category (we have an event cause which is just `EV_ET`).

Another issue that I think we need to resolve is:

* What is the correct set of events for the epoll engine to subscribe to in order to detect a close?

**Comment by azat** [comment] 2020-04-07 21:53
>In this example, we subscribe to EV_CLOSED, but we get an event that is not in this category (we have an event cause which is just EV_ET).

This should not happens for real events (IOW should be fixed), but `event_active` do not check if event is subscribed to these events or not (otherwise this will be a regression).

But actually the problem here is that `EPOLLHUP` checked before `EPOLLRDHUP`, I think that this this not right and this will be reordered you will get `EV_CLOSED` correctly, I will take a look

>What is the correct set of events for the epoll engine to subscribe to in event_assign in order to detect a close?

Not all backends supports close detection, so the rule of thumb is `EV_READ + read() == 0` or just block everything that does not support `*RDHUP`

**Comment by azat** [comment] 2020-04-08 23:26
So right now I have something like [this](https://github.com/libevent/libevent/compare/master...azat:EV_CLOSED-and-EV_ET-fixes?expand=1):

    https://github.com/azat/libevent.git EV_CLOSED-and-EV_ET-fixes

But there is one (and maybe not one, I saw some interesting stuff during looking into this) concern left - right now EV_CLOSED will not triggered via close(), so I'm thinking about changing it, but not sure

**Comment by htuch** [comment] 2020-04-10 17:36
@azat your branch resolves both my repro and the original issue, but I believe this is because no callback is occurring on the close. I'm thinking we want that, unless I'm missing something.

**Comment by azat** [comment] 2020-04-10 18:36
>but I believe this is because no callback is occurring on the close

Also please note the following:

- > Not all backends supports close detection, so the rule of thumb is EV_READ + read() == 0 or just block everything that does not support *RDHUP

- > But actually the problem here is that EPOLLHUP checked before EPOLLRDHUP, I think that this this not right and if this will be reordered you will get EV_CLOSED correctly, I will take a look

- Even if backend (i.e. poll) supports it, libevent does not, this is very easy to fix, but firstly the decision should be made what to do with that [`EPOLLRDHUP` check](https://github.com/libevent/libevent/blob/57862901095a97306e74b2944d5808051f813ed5/epoll.c#L490-L497), should it be moved upper or not, since `EPOLLHUP` will be reported with `EPOLLRDHUP` if the close was done via `close` not via `shutdown` (I looked at [libuv](https://github.com/libuv/libuv/blob/v1.x/src/unix/poll.c#L47-L61) and they do not even check for `EPOLLHUP`)

**Comment by htuch** [comment] 2020-04-12 23:38
Here's out use case; we are interested in detecting remote connection close on a network socket after we've already decided to close locally. So, we're done reading/writing and actually want to apply read back pressure on the remote. 

We basically just want a reliable way to learn when the close event has happened. Hence why we subscribe to `EV_CLOSED`; we assume an epoll backend which handles this correctly. We'd be happy subscribing to something like a hypothetical `EV_CLOSED | EV_ERROR` FWIW.

**Comment by htuch** [comment] 2020-05-01 17:00
Friendly ping on this.

**Comment by azat** [comment] 2020-05-04 21:09
>https://github.com/azat/libevent.git EV_CLOSED-and-EV_ET-fixes

Merged (c10cde4c617979e951352775a9685a47bf9c6acd), but I'm not finished with this yet

>We basically just want a reliable way to learn when the close event has happened. Hence why we subscribe to EV_CLOSED; we assume an epoll backend which handles this correctly. We'd be happy subscribing to something like a hypothetical EV_CLOSED | EV_ERROR FWIW.

Yeah, I got this, I was thinking about the backward change, but I guess I'm spending too much time for this, looking again, sorry

**Comment by azat** [comment] 2020-05-04 21:34
@htuch can you please verify? Thanks!

**Closed** 2020-05-04 21:33 UTC

**Comment by htuch** [comment] 2020-05-05 14:18
@azat that fixed it, much appreciated!
