### ISSUE TITLE
Intermittent assertion in sample code https-client

### ISSUE THREAD

**Issue by hebrerillo** [libevent/libevent#810] opened 2019-05-07 07:37 UTC
Hello!

In some executions of the sample code 'https-client' like this:

./https-client -url https://en.wikipedia.org/wiki/HTTPS

I get the following assertion:

[err] http.c:744: Assertion req != NULL failed in evhttp_connection_fail_

This assertion is intermittent and only raised with an URL using https protocol. 

Am I missing something maybe?

Thank you!!

All the best

**Comment by azat** [comment] 2019-05-07 07:58
Hi!

This assert should not bail (and I cannot reproduce it).
Which version of libevent do you use? (commit hash)

**Comment by hebrerillo** [comment] 2019-05-07 08:35
Hello Azat!

I downloaded both version 'libevent-release-2.1.7-rc' and 'libevent-2.1.8-stable' and it is happening in both versions. 

The assertion is intermittent. It happens every three or four executions.

Thanks!

**Comment by hebrerillo** [comment] 2019-05-07 08:57
Hi Azat!

When cloning the project with 'git clone' and so using libevent in the lastest commit (8701d0d3d251), the assertion is not happening anymore. 

It is happening with the two versions I mention earlier.

**Comment by azat** [comment] 2019-05-10 20:06
Hi @hebrerillo 

So i guess this can be closed, since it is fixed in master, hence next libevent release will not have this issue.

**Closed by azat** 2019-05-10 20:06 UTC
Labels: subsystem:http
