### ISSUE TITLE
Assertion failure in evbuffer_free_trailing_empty_chains

### ISSUE THREAD

**Issue by EMPanisset** [libevent/libevent#358] opened 2016-05-16 07:46 UTC
When calling function evbuffer_remove_buffer, src buffer has empty chain (chain->off is zero) in the middle of chain. This empty chain is transferred to dst buffer which causes further assertion failure in evbuffer_free_trailing_empty_chains.

I am not sure why empty chain appeared in the middle of evbuffer src's chain.
Workaround attached, at least, prevented transference of empty chain from source buffer to destination buffer and then protected against assertion failure in  evbuffer_free_trailing_empty_chains.
[evbuffer_remove_buffer.txt](https://github.com/libevent/libevent/files/265760/evbuffer_remove_buffer.txt)

**Comment by EMPanisset** [comment] 2016-05-16 18:52
Just make report more precise, I am transferring data from input of bufferevent pair (my source buffer) to another evbuffer (my destination buffer) by calling function evbuffer_remove_buffer(src, dst, len).
Data was added to output of buffer event pair by calling function evbuffer_add_reference:

evbuffer_add_reference (data, len) -> output (evbuffer) -> input (evbuffer) -> evbuffer_remove_buffer(input, dst, len) -> dst(evbuffer)

**Comment by azat** [comment] 2016-06-08 11:04
On Mon, May 16, 2016 at 11:52:41AM -0700, Eduardo Moura Panisset wrote:
> Just make report more precise, I am transferring data from input of bufferevent pair (my source buffer) to another evbuffer (my destination buffer) by calling function evbuffer_remove_buffer(src, dst, len).
> Data was added to output of buffer event pair by calling function evbuffer_add_reference:
> 
> evbuffer_add_reference (data, len) -> output (evbuffer) -> input (evbuffer) -> evbuffer_remove_buffer(input, dst, len) -> dst(evbuffer)

Hi Eduardo,

Thanks for detailed report and a patch!

But actually I think that the problem is in evbuffer_add_buffer() (in
conjunction with evbuffer_add_reference() and empth chains), can you
please test the following branch:
  git://github.com/azat/libevent.git evbuffer-empty-chains-fixes-v2

Thanks,
Azat.

**Comment by azat** [comment] 2016-06-17 12:20
Hi @EMPanisset, many thanks for testing, can you please provide simple reproducer?

**Comment by azat** [comment] 2016-06-17 13:17
Okay I think I have a reproducer

**Comment by azat** [comment] 2016-06-17 14:42
On Sat, Jun 11, 2016 at 02:01:28AM -0700, Eduardo Moura Panisset wrote:
> Hi Azat,
> 
> Thank you very much for your attention.
> 
> Unfortunately, after building from this branch, libevent crashes with an assert:

Hi Eduardo,

Can you please test next branch:
  git://github.com/azat/libevent.git evbuffer-empty-chains-fixes-v4

Thanks in advance!

**Comment by azat** [comment] 2016-06-19 19:04
@EMPanisset any news?

**Comment by EMPanisset** [comment] 2016-06-19 20:26
@azat , I can confirm that no crashes are taking place anymore for me after latest fixes.

Thank you very much for your fixes.
Eduardo Panisset.

**Comment by azat** [comment] 2016-06-19 20:51
@EMPanisset thanks! Fixed with a69e4fadcaa5a635c656886934cc23c8a25c7562

**Closed by azat** 2016-06-19 20:51 UTC
Labels: awaiting for testing
