### ISSUE TITLE
regress.exe failing to build in CI Windows vs2017 variant

### ISSUE THREAD

**Issue by nigriMSFT** [libevent/libevent#1021] opened 2020-05-21 01:46 UTC
Commit c19ebffb21eaef2f9d6726ec6fd6d797fb2c8935 seemed to be intended to resolve this issue, but the failure remains in the Windows vs2017 variant. IDK if it is still related to python paths, but python 3.7.6 does not seem to be supported on the windows-2016 or windows-2019 virtual environments.

https://github.com/actions/virtual-environments/blob/master/images/win/Windows2016-Readme.md
https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md

```
2020-05-19T08:52:03.3314983Z   Generating ../test/regress.gen.c, ../test/regress.gen.h
2020-05-19T08:52:03.3321415Z   The system cannot find the path specified.
2020-05-19T08:52:03.3779177Z C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 3. [D:\a\libevent\libevent\build\regress.vcxproj]
```

**Comment by azat** [comment] 2020-05-25 21:43
>but python 3.7.6 does not seem to be supported on the windows-2016 or windows-2019 virtual environments.

It should use latest available and AFAICS windows checks for c19ebff all passed

Did you see errors for python interpreter after this patch?

**Comment by nigriMSFT** [comment] 2020-05-26 03:05
I'm currently looking at the latest PR at the time of writing for this example. https://github.com/libevent/libevent/runs/705557950?check_suite_focus=true

In the Windows 2019 variant, we can see regress.exe is successfully built:

```
  LINK : D:\a\libevent\libevent\build\bin\Debug\regress.exe not found or not built by the last incremental link; performing full link
  regress.vcxproj -> D:\a\libevent\libevent\build\bin\Debug\regress.exe
```

In the Windows 2017 variant, we can see there was a failure that resembles the failure being addressed in c19ebff:

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 3. [D:\a\libevent\libevent\build\regress.vcxproj]`

However, even after failing to build regress.exe, CI goes on the run the regress tests. I assume it is using a cached copy from some prior CI run. Further evidence that it is using a cached copy is that the run fails on regress_WEPOLL [simpleclose_close, simpleclose_close_persist]. This is exactly the same test cases that were fixed by 06a11929511bebaaf40c52aaf91de397b1782ba2. I tried to reproduce the issue by building with VS2017 and running on Windows Server 2016, but regress passed.

**Comment by azat** [comment] 2020-05-26 09:18
Thanks!

>However, even after failing to build regress.exe, CI goes on the run the regress tests.

@ygj6 I see `$host.SetShouldExit` after `cmake --build`, does this place also requires try/catch? (although I don't see any "exceptions")

>I assume it is using a cached copy from some prior CI run.

Indeed.

**Comment by ygj6** [comment] 2020-05-26 13:05
I saw this error:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 3.
```
Usually, this error is caused by incorrect path. So I guess that there are some errors in cached build directory. But I have not reproduced it until now.
Now I will add `try/catch` for `cmake --build`.
If this error can be reproduced later, I will come back to study it.

**Comment by azat** [comment] 2020-05-26 13:08
>Usually, this error is caused by incorrect path.

Indeed, I thought about adding retry if first cmake fails with clean build directory, can you do this too?

**Comment by ygj6** [comment] 2020-05-26 13:26
For which failures need to clean build directory and retry?  All failures or some special failures?

**Comment by azat** [comment] 2020-05-26 13:33
>For which failures need to clean build directory and retry? All failures or some special failures?

For all if cmake configure step fails, i.e.

```shell
cd build
if ! cmake ... ; then
  # let's try w/o cache
  rm -fr *
  cmake ...
fi
```

**Comment by ygj6** [comment] 2020-05-27 06:52
There is an error blocking my work.
```
-- Found Git: /usr/bin/git  
fatal: No names found, cannot describe anything.
```

This error is caused by the following line in `cmake/VersionViaGit.cmake`
```
${GIT_EXECUTABLE} describe --abbrev=0
```
I have to deal with it first.

**Comment by azat** [comment] 2020-06-01 22:07
@ygj6 after you changes regress build [still fails](https://github.com/libevent/libevent/runs/716671045) on 2017:

>2020-05-28T12:12:14.0934049Z C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 3. [D:\a\libevent\libevent\build\regress.vcxproj]

But it still runs regress.exe, can you take a look?

**Comment by ygj6** [comment] 2020-06-02 01:19
Yes, this is the remaining issue in this PR: https://github.com/libevent/libevent/pull/1027#issue-423075131
I tried to reproduce it on my local computer, but not success. I will find a machine close to the github actions environment to retest.

**Comment by azat** [comment] 2020-06-02 06:00
>I tried to reproduce it on my local computer, but not success.

So there are two problems:
- regress.exe executed even if the build fails
- build of regress.exe fails

which one you are trying to reproduce?

**Comment by azat** [comment] 2020-06-02 06:05
Also it looks like you can attach to the CI worker using:
- windows - https://github.com/nelsonjchen/reverse-rdp-windows-github-actions
- osx/linux - https://github.com/marketplace/actions/debugging-with-tmate

Hope this helps

**Comment by ygj6** [comment] 2020-06-23 02:19
I tried remote debugging and it didn't reproduce the problem.
This problem may be caused by the wrong history build cache.
After 10 days of no new PR triggering CI, [the build ](https://github.com/libevent/libevent/runs/785017815?check_suite_focus=true)is now successful under vs2017. The reason should be that the wrong build cache is automatically cleared. 
[github action cache cleanup mechanism](https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy)
>GitHub will remove any cache entries that have not been accessed in over 7 days.

**Comment by azat** [comment] 2020-06-23 08:10
Ok, let's close this for now, @nigriMSFT please reopen if you will see similar picture

**Closed by azat** 2020-06-23 08:10 UTC
Labels: ci, os:windows
