### ISSUE TITLE
Deleted nameserver access in evdns_base_free

### ISSUE THREAD

**Issue by frymode** [libevent/libevent#293] opened 2015-11-23 14:39 UTC
Valgrind reports invalid read of nameserver struct there.

In `evdns_base_free_and_unlock` first all servers are [disposed with evdns_nameserver_free](https://github.com/libevent/libevent/blob/9c238deb768785c0a12d7644c5d15e6149614e74/evdns.c#L4037) but then [request_finished](https://github.com/libevent/libevent/blob/9c238deb768785c0a12d7644c5d15e6149614e74/evdns.c#L4048) is invoked where associated nameserver struct is accessed [here](https://github.com/libevent/libevent/blob/9c238deb768785c0a12d7644c5d15e6149614e74/evdns.c#L662) and maybe [here](https://github.com/libevent/libevent/blob/9c238deb768785c0a12d7644c5d15e6149614e74/evdns.c#L672).

Quick fix may be to check `global_good_nameservers` counter that is set to zero in `evdns_base_free_and_unlock` but as comment in this function says porper fix needs some kind of refcounter.

**Comment by azat** [comment] 2015-11-23 14:42
On Mon, Nov 23, 2015 at 06:39:59AM -0800, Dmitry Yakovlev wrote:
> Valgrind reports invalid read of nameserver struct there.
> 
> In `evdns_base_free_and_unlock` first all servers are [disposed with evdns_nameserver_free](https://github.com/libevent/libevent/blob/9c238deb768785c0a12d7644c5d15e6149614e74/evdns.c#L4037) but then [request_finished](https://github.com/libevent/libevent/blob/9c238deb768785c0a12d7644c5d15e6149614e74/evdns.c#L4048) is invoked where associated nameserver struct is accessed [here](https://github.com/libevent/libevent/blob/9c238deb768785c0a12d7644c5d15e6149614e74/evdns.c#L662) and maybe [here](https://github.com/libevent/libevent/blob/9c238deb768785c0a12d7644c5d15e6149614e74/evdns.c#L672).

Hi Dmitry,

Nice catch!
Just today I fixed this, can you please test next branch:
    https://github.com/azat/libevent.git dns-related-fixes-v4

Thanks,
Azat.

**Comment by azat** [comment] 2015-11-25 10:14
Must be fixed by 14f84bbdc77d90b1d936076661443cdbf516c593 (but it is better to test the whole patchset not only this patch, since there are other issues around).

**Comment by azat** [comment] 2015-12-14 20:44
I'm closing this, @frymode if you will reproduce this again, please reopen.

**Closed by azat** 2015-12-14 20:44 UTC
Labels: awaiting for testing, fixed
