### ISSUE TITLE
release-2.1.8-stable MINGW64  automake vs cmake

### ISSUE THREAD

**Issue by CaeruleusAqua** [libevent/libevent#605] opened 2018-03-07 14:22 UTC
I am use msys2 and tried compiling release-2.1.8-stable.

Seems that compiling is working with automake but not with cmake.
(with  MSYS Makefiles and MinGW Generator)

[cmake.log](https://github.com/libevent/libevent/files/1789427/cmake.log)

[automake.log](https://github.com/libevent/libevent/files/1789428/automake.log)

**Comment by azat** [comment] 2018-04-22 22:52
Hi!

Sorry for **huge** delay.
Can you verify that referenced patch fixes the issue?

**Comment by CaeruleusAqua** [comment] 2018-04-24 08:39
Hi,

no, still the same error!

I took a closer look at the problem and it seems that all "CHECK_FUNCTION_EXISTS_EX" checks fail. The normal "CHECK_FUNCTION_EXISTS" function seems to work. I'm not sure why you created your own, but I'm sure it has some side effects when I just replace the function.

**Comment by azat** [comment] 2018-04-24 09:48
Have you remove the cmake cache before trying attached patch?

Can you tar.gz all `CMAKE_BINARY_DIR` and send it to me somehow? (maybe I will find exact commands/sources of `check_function_exists_ex`)

**Comment by CaeruleusAqua** [comment] 2018-04-24 12:42
> Have you remove the cmake cache before trying attached patch?

Of course I did (multiple times).
[build.tar.gz](https://github.com/libevent/libevent/files/1942744/build.tar.gz)

**Comment by azat** [comment] 2018-04-24 19:49
Hm, it still cannot find the function.
``` 
/C/msys64/mingw64/bin/gcc.exe   -Wall -Wswitch -fno-strict-aliasing -DCHECK_FUNCTION_EXISTS=strtok_r   -FIwinsock2.h -FIws2tcpip.h -o CMakeFiles/cmTC_9adc2.dir/CheckFunctionExistsEx.c.obj   -c /C/msys64/h>
C:/msys64/home/scholle/external/libevent/cmake/CheckFunctionExistsEx.c: In function 'main':
<command-line>:0:23: error: 'strtok_r' undeclared (first use in this function)
C:/msys64/home/scholle/external/libevent/cmake/CheckFunctionExistsEx.c:15:15: note: in expansion of macro 'CHECK_FUNCTION_EXISTS'
   void * p = &CHECK_FUNCTION_EXISTS;
```

And the reason for this is that shipped with libevent version of CheckFunctionExistsEx() needs the function to be defined for win32. And I don't think that for win32 it is required although I don't know their compilers specifics, but I think that cmake's CheckFunctionExists.c must handle this correctly, so I just synced them.

So can you try d517fe98?

p.s. ugh we should remove those `*Ex`, but let's fix this fast and refactor later.

**Comment by CaeruleusAqua** [comment] 2018-04-25 07:56
The check now works completely, 

but now I'm getting some undefined references to SSL.

[build.log](https://github.com/libevent/libevent/files/1945980/build.log)

The problem seems to be the second `target_link_libraries` in the `add_sample_prog` macro when SSL is enabled. Since it overwrites all previous dependencies.

Interestingly, this does not occur under Linux. CMake seems to behave differently there.

Anyway, here's a cross platform solution (testet on Windows 10 and Ubuntu 17.10):

```
#
# Samples.
#
macro(add_sample_prog ssl name)
    add_executable(${name} ${ARGN})

    if (${ssl})
        set(SSL_LIBS event_openssl_static)
        set(SSL_DEPS event_openssl_static)
    endif()

    target_link_libraries(${name}
                          event_extra_static
                          event_core_static
                          ${LIB_APPS}
                          ${LIB_PLATFORM}
                          ${SSL_LIBS})

    add_dependencies(${name}
                     event_core_static
                     event_extra_static
                     ${SSL_DEPS})
endmacro()
```

**Comment by azat** [comment] 2018-04-25 20:01
> The check now works completely
Can you check VS build too? (just our of curiosity)

> The problem seems to be the second target_link_libraries in the add_sample_prog macro when SSL is enabled. Since it overwrites all previous dependencies.
Hm, interesting. But I think that cmake works correctly (otherwise this will be insane), but order of how libraries passed to the linker breaks this, can you verify this?

**Comment by azat** [comment] 2018-08-01 06:44
After I had fixed my vagrant boxes, I can confirm that both builds should be fine. Closed.

**Closed by azat** 2018-08-01 06:44 UTC
Labels: build:cmake, os:win32
