### ISSUE TITLE
Does need wait a little after call shutdown, then call closesocket in http.c ?

### ISSUE THREAD

**Issue by cosmosir** [libevent/libevent#1085] opened 2020-08-28 10:16 UTC
libevent-2.1.12-stable
file >> http.c 
function >> evhttp_connection_free
line >> 1263

code >>
if (evcon->fd != -1) {
		shutdown(evcon->fd, EVUTIL_SHUT_WR);
		if (need_close)
			evutil_closesocket(evcon->fd);
	}

Do need to confirm that the data has been sent after shutdown, then close socket ?

**Comment by azat** [comment] 2020-08-28 22:16
>Does need wait a little after call shutdown, then call closesocket in http.c ? #1085

What for? No, you don't need to wait between these two syscalls (otherwise it will be to trickery)

**Comment by cosmosir** [comment] 2020-08-29 08:47
httpclient add the header "Expect:100-continue", sometimes httpserver just respond "HTTP/1.1 200 OK" only.
httpclient can't receive this reply correctly( miss other data, the header Content-Length and so on)

the Call Stack:
>	event_core.dll!evbuffer_launch_write_(evbuffer * buf, __int64 at_most, event_overlapped * ol) line 226	C
 	event_core.dll!bev_async_consider_writing(bufferevent_async * beva) line 238	C
 	event_core.dll!be_async_outbuf_callback(evbuffer * buf, const evbuffer_cb_info * cbinfo, void * arg) line 322	C
 	event_core.dll!evbuffer_run_callbacks(evbuffer * buffer, int running_deferred) line 510	C
 	event_core.dll!evbuffer_invoke_callbacks_(evbuffer * buffer) line 531	C
 	event_core.dll!evbuffer_add_vprintf(evbuffer * buf, const char * fmt, char * ap) line 2894	C
 	event_core.dll!evbuffer_add_printf(evbuffer * buf, const char * fmt, ...) line 2914	C
 	event_extra.dll!evhttp_make_header_response(evhttp_connection * evcon, evhttp_request * req) line 540	C
 	event_extra.dll!evhttp_make_header(evhttp_connection * evcon, evhttp_request * req) line 621	C
 	event_extra.dll!evhttp_send(evhttp_request * req, evbuffer * databuf) line 2854	C
 	event_extra.dll!evhttp_send_reply(evhttp_request * req, int code, const char * reason, evbuffer * databuf) line 2864	C
 	http-server.exe!dump_request_cb(evhttp_request * req, void * arg) line 177	C
 	http-server.exe!send_document_cb(evhttp_request * req, void * arg) line 199	C
 	event_extra.dll!evhttp_handle_request(evhttp_request * req, void * arg) line 3502	C
 	event_extra.dll!evhttp_connection_done(evhttp_connection * evcon) line 876	C
 	event_extra.dll!evhttp_read_body(evhttp_connection * evcon, evhttp_request * req) line 1122	C
 	event_extra.dll!evhttp_read_cb(bufferevent * bufev, void * arg) line 1156	C
 	event_core.dll!bufferevent_run_deferred_callbacks_locked(event_callback * cb, void * arg) line 168	C
 	event_core.dll!event_process_active_single_queue(event_base * base, evcallback_list * activeq, int max_to_process, const timeval * endtime) line 1699	C
 	event_core.dll!event_process_active(event_base * base) line 1783	C
 	event_core.dll!event_base_loop(event_base * base, int flags) line 2006	C
 	event_core.dll!event_base_dispatch(event_base * event_base) line 1818	C


when call 
```
evbuffer_add_printf(bufferevent_get_output(evcon->bufev),
	    "HTTP/%d.%d %d %s\r\n",
	    req->major, req->minor, req->response_code,
	    req->response_code_line);
```
call WSASend data to httpclient, other data don't send anymore.

**Comment by azat** [comment] 2020-08-29 22:03
>sometimes httpserver just respond "HTTP/1.1 200 OK" only.
>httpclient can't receive this reply correctly( miss other data, the header Content-Length and so on)

Can you provide correct simple reproducer?

**Comment by cosmosir** [comment] 2020-08-31 11:57
[NetHttpClient.zip](https://github.com/libevent/libevent/files/5150126/NetHttpClient.zip)
use libevent-2.1.12-stable\sample\httpserver
command parameter -p21303 -I test

**Comment by azat** [comment] 2020-09-01 19:55
>NetHttpClient1.zip

No .exe, plain .c

**Comment by azat** [comment] 2021-01-03 13:24
Closing, due to lack of reply, feel free to reopen

**Closed by azat** 2021-01-03 13:24 UTC
Labels: type:q
