### ISSUE TITLE
 time-test.c

### ISSUE THREAD

**Issue by shbfxwzf** [libevent/libevent#859] opened 2019-07-29 09:17 UTC
For time-test.c file, under Linux, when the -O2 option is used for optimization compilation, the compiled program can get correct results, but if the -O2 option is not used, a segment error will occur

**Comment by azat** [comment] 2019-07-30 07:14
Can you please post the error (with the stacktrace where the SIGSEGV happens) ?

**Comment by shbfxwzf** [comment] 2019-07-30 08:36
I got this by debugging under GDB
![pic_error](https://user-images.githubusercontent.com/25627685/62113928-2128f580-b2e8-11e9-9c85-f63f2f4da92c.PNG)

**Comment by azat** [comment] 2019-08-05 21:58
>I got this by debugging under GDB

So, first of all it is 2.0.x

>What should I do

Can you install debug symbols or if you do not have such ability compile libevent 2.0.23-beta from sources (this should be pretty trivial todo, since libevent do not have lot's of dependencies) and check if you can reproduce it?

**Comment by shbfxwzf** [comment] 2019-08-06 00:52
I cloned the latest libevent source code and compiled and installed it according to the instructions，

$ ./configure
$ make
$ make verify   # (optional)
$ sudo make install

The installation went smoothly without any errors，
As for the debugging symbol you mentioned, I have used the option of -g when compiling.
I hope to get further help from you if there is anything left out

**Comment by azat** [comment] 2019-08-08 08:08
>For time-test.c file

I just noticed that you are using time-test.c from upstream with libevent 2.0, though they do not have meaningful diff.

>I cloned the latest libevent source code and compiled

If you get the latest sources, then it is upstream, not 2.0.23, am I right?
If so then you program still uses 2.0 version, you can verify this with `ldd /path/to/so`

>I have used the option of -g when compiling.

Did you pass it to the libevent?

>I hope to get further help from you if there is anything left out

So here is what I would do if I got this:

```shell
git clone --branch=release-2.0.23-beta https://github.com/libevent/libevent.git libevent-2.0.23
cd libevent-2.0.23
./autogen.sh
./configure --disable-openssl
make -j
./sample/time-test
```

And after this steps I still did not receive any errors...

If you still experience this SIGSEGV, please run under valgrind, like this (after all steps above):

```shell
LD_LIBRARY_PATH=.libs valgrind sample/.libs/time-test
```
(`LD_LIBRARY_PATH` is required here since `sample/time-test` is a shell wrapper that does something like the command above, and to avoid extra `fork()` for valgrind we expanding this)

**Comment by azat** [comment] 2019-09-02 21:56
Closing, due to lack of details

**Closed by azat** 2019-09-02 21:56 UTC
Labels: libevent-2.0, status:unconfirmed
