### ISSUE TITLE
win10 Error	

### ISSUE THREAD

**Issue by lcals** [libevent/libevent#1096] opened 2020-09-14 15:43 UTC
env :  win10  vs2019   vcpkg install libevent:x64-windows-static
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __imp_if_nametoindex referenced in function evutil_inet_pton_scope		**\event.lib(evutil.c.obj)	1	

ubunut normal

**Comment by azat** [comment] 2020-09-14 18:43
>Error LNK2019 unresolved external symbol __imp_if_nametoindex referenced in function evutil_inet_pton_scope **\event.lib(evutil.c.obj) 1


Introduced here #923
@ygj6 can you take a look?

**Comment by ygj6** [comment] 2020-10-09 07:20
I executed `vcpkg install libevent:x64-windows-static` in `win10 vs2019` environment and the result was normal:

```
>vcpkg install libevent:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
    libevent[core,thread]:x64-windows-static
Detecting compiler hash for triplet x64-windows-static...
Starting package 1/1: libevent:x64-windows-static
Building package libevent[core,thread]:x64-windows-static...
Could not locate cached archive: C:\Users\xxx\AppData\Local\vcpkg\archives\7f\7fd1bc6eaa086b5110dbe51a082b3ec8dda96fc2.zip
-- Downloading https://github.com/libevent/libevent/archive/release-2.1.12-stable.tar.gz...
-- Extracting source D:/vcpkg/downloads/libevent-libevent-release-2.1.12-stable.tar.gz
-- Applying patch fix-file_path.patch
-- Applying patch fix-LibeventConfig_cmake_in_path.patch
-- Using source at D:/vcpkg/buildtrees/libevent/src/.12-stable-79b01d8892.clean
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Installing: D:/vcpkg/packages/libevent_x64-windows-static/share/libevent/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\xxx\AppData\Local\vcpkg\archives\7f\7fd1bc6eaa086b5110dbe51a082b3ec8dda96fc2.zip
Building package libevent[core,thread]:x64-windows-static... done
Installing package libevent[core,thread]:x64-windows-static...
Installing package libevent[core,thread]:x64-windows-static... done
Elapsed time for package libevent:x64-windows-static: 1.527 min

Total elapsed time: 1.655 min

The package libevent:x64-windows-static provides CMake targets:

    find_package(Libevent CONFIG REQUIRED)
    target_link_libraries(main PRIVATE libevent::core libevent::extra)
```
@lcals Could you please provide more detailed steps to reproduce?

**Comment by azat** [comment] 2021-01-03 13:23
Closing, due to lack of reply, feel free to reopen

**Closed by azat** 2021-01-03 13:23 UTC
Labels: os:windows
