### ISSUE TITLE
Epoll edge-triggered setting lost when manipulating multiple events for same fd

### ISSUE THREAD

**Issue by ikouvelas** [libevent/libevent#636] opened 2018-05-23 12:08 UTC
After two or more events have been registered for the same file descriptor using EV_ET, if one of the events is deleted, then the epoll_ctl() call issued by libevent drops the EPOLLET flag resulting in level triggered notifications.

The issue exists in both 2.0.22 and 2.1.8 code.

It can be reproduced with the following program:
[libevent_issue.c.txt](https://github.com/libevent/libevent/files/2030823/libevent_issue.c.txt)

The output is:
> Adding event1
> epoll_ctl epfd=3 fd=6 op=ADD events=80000004 (OutEt) ret=0
> Adding event2
> epoll_ctl epfd=3 fd=6 op=MOD events=80000005 (InOutEt) ret=0
> Deleting event2
> epoll_ctl epfd=3 fd=6 op=MOD events=4 (Out) ret=0
> Done

Note that after deleting event2, the MOD operation issued by libevent only has the "Out" event flag and not the "Et" flag set.

The following patches fix the issue:
[libevent-2.0.22-edge-triggered-multiple-events.patch.txt](https://github.com/libevent/libevent/files/2030889/libevent-2.0.22-edge-triggered-multiple-events.patch.txt)
[libevent-2.1.8-edge-triggered-multiple-events.patch.txt](https://github.com/libevent/libevent/files/2030891/libevent-2.1.8-edge-triggered-multiple-events.patch.txt)

The output with the fix applied is:
> Adding event1
> epoll_ctl epfd=3 fd=6 op=ADD events=80000004 (OutEt) ret=0
> Adding event2
> epoll_ctl epfd=3 fd=6 op=MOD events=80000005 (InOutEt) ret=0
> Deleting event2
> epoll_ctl epfd=3 fd=6 op=MOD events=80000004 (OutEt) ret=0
> Done

Note that "Et" is now set in the MOD operation when deleting event2.

**Comment by azat** [comment] 2018-10-28 20:32
Hi @ikouvelas 

Thanks, nice catch!
I will take a closer look.

In the meantime could you resend them as a normal (that includes subject and description) git patch (or as a pull request, although I do not insist) or at least send me your name/email (so I that I can add it to the patch)? (post here or send me a private email)

Also any chance you can add a regression test for this?

P.S. sorry for the giant delay

**Comment by azat** [comment] 2018-10-30 08:14
Plus I'm curious why do you not use `ev->ev_events` in `evmap_io_del_()`?

**Comment by ikouvelas** [comment] 2018-10-30 16:03
Including git patch with regression test.

[libevent-636-epoll-ET-multiple-event.patch.txt](https://github.com/libevent/libevent/files/2530418/libevent-636-epoll-ET-multiple-event.patch.txt)

I think the reason I did not use ev->ev_events in evmap_io_del() is that I felt it was safer to get the ET setting from the remaining valid event.

**Comment by azat** [comment] 2018-10-30 18:31
Also are you still interesting in libevent 2.0?

**Comment by azat** [comment] 2018-10-30 21:12
Fixed the issue with changelists and looking int kqueue

**Comment by azat** [comment] 2018-10-30 22:26
So I just pushed this patch set into the upstream, that includes:
- test cleanup
- enhancement to cover kqueue (see comment in test)
- changelist fixes
- ET flat into event_base_dump_events() (just for fun)
(test with epoll/epoll-changelist/kqueue)

I closed this issue since not really sure that I want to release yet another 2.0 release, but if there will be enough people voting for this I'm fine with doing this one more time.

Thank you for the detailed report!

**Comment by azat** [comment] 2018-10-30 22:30
(reopen due to this one requires backporting to 2.1.9)

**Comment by ikouvelas** [comment] 2018-10-31 11:05
Thanks for taking care of this issue!

**Comment by azat** [comment] 2018-11-04 18:50
@ikouvelas 

>Also are you still interesting in libevent 2.0?

**Comment by azat** [comment] 2019-03-03 20:35
2.1.9-beta released in 9c75c24caa7689c010864579e27b159665c8dd63
2.0.23-beta release in 4294867cbc896f43cda84930d4355227e7b55fba

Closing

**Closed by azat** 2019-03-03 20:35 UTC
Labels: backport:2.1
