### ISSUE TITLE
event_errx processing a read callback on a cancelled evhttp_request

### ISSUE THREAD

**Issue by akrieger** [libevent/libevent#315] opened 2016-01-13 21:17 UTC
I'm falling into an internal libevent assert case when cancelling an active evhttp request from outside of its chunk callback. This reproduces fairly regularly, where I start a download, cancel it, create a new download (same resource, using Range headers to do a partial download), and cancelling it again. I've hit this assert 3/5 attempts (twice in a row, twice okay, then again). I'm using libevent master at commit 809bb39b2b7b632c86337877b483520d997cd5db
Author: Azat Khuzhin <a3at.mail@gmail.com>
Date:   Mon Nov 23 13:52:31 2015 +0300

![libevent_bad](https://cloud.githubusercontent.com/assets/667719/12307935/39b28924-b9f7-11e5-83a0-9602f108adfe.PNG)

https://github.com/libevent/libevent/blob/master/http.c#L1120-L1125

Stack trace:
![libevent_stack](https://cloud.githubusercontent.com/assets/667719/12307960/69c6913c-b9f7-11e5-91cc-e2b0f6b13840.PNG)

event_exit:108
event_errx:163
evhttp_read_cb:1127
bufferevent_run_deferred_callbacks_locked:152
event_process_active_single_queue:1650
event_process_active:1735
event_base_loop:1957
event_base_dispatch:1769

**Comment by azat** [comment] 2016-01-14 01:05
On Wed, Jan 13, 2016 at 01:17:15PM -0800, akrieger wrote:
> I'm falling into an internal libevent assert case when cancelling an active evhttp request from outside of its chunk callback. This reproduces fairly regularly, where I start a download, cancel it, create a new download (same resource, using Range headers to do a partial download), and cancelling it again. I've hit this assert 3/5 attempts (twice in a row, twice okay, then again). I'm using libevent master at commit 809bb39b2b7b632c86337877b483520d997cd5db

Can you post a small reproducer?
(And if you can write a regression for http layer, that would be great).

Thanks,
Azat.

**Comment by akrieger** [comment] 2016-01-14 06:11
I'll do my best, it's a bit of a crunch here at work. Not sure how quickly I'll be able to get back to you on this.

> (And if you can write a regression for http layer, that would be great).

What do you mean?

**Comment by azat** [comment] 2016-01-14 09:03
On Wed, Jan 13, 2016 at 10:11:35PM -0800, akrieger wrote:
> I'll do my best, it's a bit of a crunch here at work. Not sure how quickly I'll be able to get back to you on this.

Thanks, I'll appreciate.

> What do you mean?

I mean, write this code in test/regress_http.c, but this not
necessarily.

**Comment by azat** [comment] 2016-04-18 10:51
On Wed, Jan 13, 2016 at 10:11:35PM -0800, akrieger wrote:
> I'll do my best, it's a bit of a crunch here at work. Not sure how quickly I'll be able to get back to you on this.

HI @akrieger,

Seems that you don't have time for this, but I think that latest changes
can fix the issue for you, can you please give a try latest libevent
from upstream (d5e634a80e4615946dc40833d04e2f3f9ba075da)?

In particular I think that next patches can fix you issue:
- 5830e331e17dc16dfa191484561f5b3abf1d55ba ("Merge branch 'bufev-cancellations-v5'")

And 5830e331e17dc16dfa191484561f5b3abf1d55ba will not help you, then it
will be great to have a reproducer.

Refs: #333

Thanks,
Azat.

**Comment by azat** [comment] 2016-05-09 23:21
@akrieger closing this one, please reopen it if it is still an issue for you **after 38e0f4a5d6a0a4716c875ad84e499538596e4aa9** (just a random `sha1` that mustn't have this issue)

**Closed** 2016-05-09 23:22 UTC
Labels: awaiting for reply

**Comment by sclei** [comment] 2019-08-20 11:23
Hello, @azat,  I also encountered the same problem in 2.1.11.
I opened **a new thread** to process the http request in the callback function, and used the evhttp_send related function or the replay function to reply to the client in this new thread.  **Sometimes I run into this problem, usually when the client's request is sent fast.**
I want to know if the evhttp module does not support calling evhttp functions in **multiple threads**  at the same time, or this is an unknown bug.
Since the problem in the stack shows that the problem is dispatched by event, I don't know where the problem with my code is, and if possible I will write a demo to reproduce it.

#### My stack trace
```shell
#0  0x00007f62a40e44f5 in raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1  0x00007f62a40e5cd5 in abort () at abort.c:92
#2  0x00007f62a54429ba in event_exit () from /usr/lib/libevent-2.1.so.7
#3  0x00007f62a5442e9b in event_errx () from /usr/lib/libevent-2.1.so.7
#4  0x00007f62a543000d in bufferevent_decref_and_unlock_ () from /usr/lib/libevent-2.1.so.7
#5  0x00007f62a543a29a in event_process_active_single_queue () from /usr/lib/libevent-2.1.so.7
#6  0x00007f62a543acbf in event_base_loop () from /usr/lib/libevent-2.1.so.7
#7  0x0000000000433700 in MyNamespace::Server::start() ()
#8  0x0000000000431dfe in main ()
```
