### ISSUE TITLE
http request memory leaks

### ISSUE THREAD

**Issue by public-rtos** [libevent/libevent#1073] opened 2020-08-03 02:47 UTC
I using libevent2.1.8 for my project, when i make  http request connect greater than 1000 times, the task manager's process tab was found the memory use 100Mbytes, and when i make http request connect greater than 2000 times, the memory use 200Mbytes.why?

**Comment by ploxiln** [comment] 2020-08-03 04:51
This is most likely due to a bug in your code.

There is a possibility that there is a leak in libevent, but you would need to use valgrind or address-sanitizer to debug the root cause yourself, and provide a small code sample which can reproduce the problem, and show that it exists with the latest stable release (libevent-2.1.12).

For what it's worth, I authored a service which uses evhttp to serve a couple simple http endpoints and make some simple http requests to another service, and has no memory leaks (verified with valgrind over a few days). It is currently built with libevent-2.1.11 but was previously built with libevent-2.1.8.

**Comment by ProjectDInitial** [comment] 2020-08-27 08:59
May be caused by ptmalloc, try to call malloc_trim(0).

**Comment by public-rtos** [comment] 2020-08-31 00:27
Thank you very much, let me try it.
&nbsp;

刘兵（CTO）
广州市航易信息科技有限公司
电话：020-62321472/13751892699
传真：020-62321243
地址：广州市天河区黄埔大道西163号富星商贸大厦15L



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yu June Leung"<notifications@github.com&gt;; 
发送时间: 2020年8月27日(星期四) 下午5:00
收件人: "libevent/libevent"<libevent@noreply.github.com&gt;; 
抄送: "public_rtos"<272903152@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [libevent/libevent] http request memory leaks (#1073)





 
May be caused by ptmalloc, try to call malloc_trim(0).

**Comment by azat** [comment] 2021-01-03 13:24
Closing, due to lack of reply, feel free to reopen

**Closed by azat** 2021-01-03 13:24 UTC
Labels: subsystem:http, type:q
