### ISSUE TITLE
Libevent perturbs application calls to rand()

### ISSUE THREAD

**Issue by rhc54** [libevent/libevent#384] opened 2016-08-03 03:13 UTC
The OpenMPI community has received several complaints recently about applications whose use of rand() is being perturbed by our library. Investigation found that libevent is, among others, calling rand() internally. This perturbs the application.

We found a workaround whereby we can define rand to point to our own function, which generates a random number using a solution other than the standard library's rand function. However, we wanted to bring it to your attention as others may also be encountering this issue, and you may want to revise libevent itself to avoid the problem.

We'd be happy to share the solution with you, if you are interested.

**Comment by jsquyres** [comment] 2016-08-03 13:55
If you care, here is the alternative to rand(3) that we use:

https://github.com/open-mpi/ompi/blob/master/opal/util/alfg.c

We can then call `opal_srand()` and `opal_rand()` instead of `srand(3)` and `rand(3)`.

**Comment by azat** [comment] 2016-08-04 08:37
On Tue, Aug 02, 2016 at 08:13:48PM -0700, rhc54 wrote:
> The OpenMPI community has received several complaints recently about applications whose use of rand() is being perturbed by our library. Investigation found that libevent is, among others, calling rand() internally. This perturbs the application.

Simple grep through sources and I can't find any of the following:
- rand
- rand_r
- srand # only in test-ratelimit.c
- random

Can you share some callers of rand() in libevent?

Thanks,
Azat.

P.S. Also we have arc4random.

**Comment by jsquyres** [comment] 2016-08-04 14:04
You are correct!  I don't see any calls to `rand()` in the current libevent code base, either.

We are using an older version of libevent that still has calls to `rand()`.  Sorry for the noise!

**Comment by jsquyres** [comment] 2016-08-04 14:34
When I replied earlier, I did a git clone from https://github.com/libevent/libevent, confirmed what you said (no calls to `rand()` and friends), and then looked at the libevent version in `configure.ac`, and saw that it is set to `2.1.5-beta`.  We're using v2.0.22 in Open MPI, and I assumed "whoops; we must be using an old version in Open MPI."

But @rhc54 just pointed out to me that libfabric.org still has 2.0.22 as the latest stable download available.  So I wasn't *entirely* off-base -- but you can probably still close this issue because you've clearly already fixed the issue in the code base.  😄 

Just curious: do you have an ETA for a post-2.0.22 stable release?

**Comment by azat** [comment] 2016-08-07 13:06
Well, we are trying to push releases ASAP (see #348, #285), and it will be fixed only in *2.1.x* (I don't sure that backporting this to *2.0* will be easy). Sadly, but I can't tell more precisely about *ETA*.

**Comment by azat** [comment] 2016-08-07 13:08
Fixed in e86af4b7e56ed5b7050cb4f41ae534f54748598c

**Comment by gpaulsen** [comment] 2016-09-16 22:36
It looks like there has never been a stable 2.1.x release, even though 2.1.1 had it's first unstable release on 2012-04-03.
Does this mean that the ETA for a stable 2.1.x release is 4 or more years away?

**Comment by azat** [comment] 2016-09-18 07:08
> It looks like there has never been a stable 2.1.x release, even though
2.1.1 had it's first unstable release on 2012-04-03.
> Does this mean that the ETA for a stable 2.1.x release is 4 or more years
away?

Sadly but it looks like this, we are working hard to release 2.1 stable,
but for now only 2.1.6 beta, though it is pretty stable from my POW, but we
need some time to validate this.

**Comment by gpaulsen** [comment] 2016-09-22 18:39
Thanks for the reply.
So, can you comment on what's required for a stable release?  Tests to pass at a certain level?  I'm trying to gage how long we should delay our release of our own Open MPI based MPI, or when we can pickup libeven 2.1.x which has some fixes our customers are requesting.

**Comment by azat** [comment] 2016-09-25 16:05
Sorry for the delay.

> So, can you comment on what's required for a stable release? Tests to
pass at a certain level?

Yeah, and also a lot of configurations to test on:
- os
- disable/enable some functionality at compile time

You can take a look at
https://github.com/libevent/libevent/wiki/ReleaseChecklist

For more information

> I'm trying to gage how long we should delay our release of our own Open
MPI based MPI, or when we can pickup libeven 2.1.x which has some fixes our
customers are requesting.

2.1.6-beta is already available, you can get it from libevent.org.
And it will be great, if you can give it a try!

P.S. I really hope that for 2.0.x we need ~ month.

**Comment by gpaulsen** [comment] 2016-09-26 15:21
Okay, Thanks for info, and link.  This week, IBM Spectrum MPI (based on Open MPI v2.x) will add the beta for some internal testing, and feedback any issues we find.

**Comment by jsquyres** [comment] 2016-09-26 16:14
@gpaulsen @jjhursey It would be great to see a pull request on Open MPI with the beta libfabric.  😄

**Comment by gpaulsen** [comment] 2016-09-27 02:09
A) This is libevent. :)
B) I don't know that we want Open MPI to use beta libfabric.  We'll know more after some testing.  Perhaps the beta in the master, but wait for upgrading a release branch until it releases?

**Comment by azat** [comment] 2016-10-16 08:47
So, can you/we close this?

**Comment by jsquyres** [comment] 2016-10-16 12:44
Yes, I think this can be closed.

**Closed** 2016-10-16 13:47 UTC
