### ISSUE TITLE
Can not find any libraries for libevent on win10 with triplets:x64-windows

### ISSUE THREAD

**Issue by rascalrr** [libevent/libevent#1107] opened 2020-10-14 02:56 UTC
OS: win10 2004
VCPKG:2020.06.15-nohash

CMakeLists.txt
```
find_package(Libevent CONFIG REQUIRED)
target_link_libraries(TestCMakeLinux PRIVATE libevent::core libevent::extra)
```

Output
```
[CMake] -- The C compiler identification is MSVC 19.27.29112.0
[CMake] -- The CXX compiler identification is MSVC 19.27.29112.0
[CMake] -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe
[CMake] -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - works
[CMake] -- Detecting C compiler ABI info
[CMake] -- Detecting C compiler ABI info - done
[CMake] -- Detecting C compile features
[CMake] -- Detecting C compile features - done
[CMake] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe
[CMake] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - works
[CMake] -- Detecting CXX compiler ABI info
[CMake] -- Detecting CXX compiler ABI info - done
[CMake] -- Detecting CXX compile features
[CMake] -- Detecting CXX compile features - done
[CMake] -- Found libevent include directory: C:/vcpkg/installed/x64-windows/include
[CMake] CMake Warning at C:/vcpkg/installed/x64-windows/share/libevent/LibeventConfig.cmake:65 (message):
[CMake]   Your libevent library does not contain a core component!
[CMake] Call Stack (most recent call first):
[CMake]   C:/vcpkg/installed/x64-windows/share/libevent/LibeventConfig.cmake:78 (message_if_needed)
[CMake]   C:/vcpkg/installed/x64-windows/share/libevent/LibeventConfig.cmake:140 (no_component_msg)
[CMake]   C:/vcpkg/installed/x64-windows/share/libevent/LibeventConfig.cmake:145 (find_event_lib)
[CMake]   C:/vcpkg/scripts/buildsystems/vcpkg.cmake:496 (_find_package)
[CMake]   CMakeLists.txt:18 (find_package)
[CMake] CMake Warning at C:/vcpkg/installed/x64-windows/share/libevent/LibeventConfig.cmake:65 (message):
[CMake]   Your libevent library does not contain a extra component!
[CMake] Call Stack (most recent call first):
[CMake]   C:/vcpkg/installed/x64-windows/share/libevent/LibeventConfig.cmake:78 (message_if_needed)
[CMake]   C:/vcpkg/installed/x64-windows/share/libevent/LibeventConfig.cmake:140 (no_component_msg)
[CMake]   C:/vcpkg/installed/x64-windows/share/libevent/LibeventConfig.cmake:145 (find_event_lib)
[CMake]   C:/vcpkg/scripts/buildsystems/vcpkg.cmake:496 (_find_package)
[CMake]   CMakeLists.txt:18 (find_package)
[CMake] CMake Error at C:/vcpkg/installed/x64-windows/share/libevent/LibeventConfig.cmake:172 (message):
[CMake]   Can not find any libraries for libevent.
[CMake] Call Stack (most recent call first):
[CMake]   C:/vcpkg/scripts/buildsystems/vcpkg.cmake:496 (_find_package)
[CMake]   CMakeLists.txt:18 (find_package)
[CMake] -- Configuring incomplete, errors occurred!
[CMake] See also "C:/Test/OnlyTest/TestCMakeLinux/out/build/x64-Debug/CMakeFiles/CMakeOutput.log".
```

x64:linux and x:64-windows-static is normal.

**Comment by azat** [comment] 2020-10-20 19:38
>[CMake] CMake Warning at C:/vcpkg/installed/x64-windows/share/libevent/LibeventConfig.cmake:65 (message):
>[CMake]   Your libevent library does not contain a extra component!

Can you attach `C:/vcpkg/installed/x64-windows/share/libevent/LibeventConfig.cmake`?
And also what version of libevent do you have?

**Comment by azat** [comment] 2020-10-20 19:38
Cc: @ygj6 (windows stuff)

**Comment by rascalrr** [comment] 2020-10-21 04:09
@azat Thank for your response.

Libevent version:
```
PS C:\vcpkg> .\vcpkg list libevent
libevent:x64-linux                                 2.1.12           An event notification library
libevent:x64-windows                               2.1.12           An event notification library
libevent:x64-windows-static                        2.1.12           An event notification library
libevent:x86-windows                               2.1.12           An event notification library
libevent:x86-windows-static                        2.1.12           An event notification library
libevent[thread]:x64-linux                                          Support for thread
libevent[thread]:x64-windows                                        Support for thread
libevent[thread]:x64-windows-static                                 Support for thread
libevent[thread]:x86-windows                                        Support for thread
libevent[thread]:x86-windows-static                                 Support for thread
```
I attached cmake file in zip.
[LibeventConfig.zip](https://github.com/libevent/libevent/files/5413188/LibeventConfig.zip)

**Comment by azat** [comment] 2020-10-23 19:31
Sorry for the delay

>LibeventConfig.zip

```cmake
# IMPORTED targets from LibeventTargets.cmake
set(LIBEVENT_STATIC_LIBRARIES "")
set(LIBEVENT_SHARED_LIBRARIES "core;extra")
```

So looks like it searches only for static libraries, so you have one of the following:
- `LIBEVENT_STATIC_LINK=TRUE`
- Or modified `CMAKE_FIND_LIBRARY_SUFFIXES_SAVE` (lack of `.dll` in it)

If you don't see where you have such things you can try explicitly adjust those variables just before `find_package` (and hope that `C:/vcpkg/scripts/buildsystems/vcpkg.cmake` does not do anything with these variables)

>x64:linux and x:64-windows-static is normal.

And this confirms my theory.

**Comment by rascalrr** [comment] 2020-10-26 05:26
@azat Thank for your advice.
I do the follows to support static lib and dynamic dlls.

1. Add static core for static libs.
```
LIBEVENT_STATIC_LINK=TRUE
set(LIBEVENT_STATIC_LIBRARIES "") => set(LIBEVENT_STATIC_LIBRARIES "core;extra")
```
2. Remove NO_DEFAULT_PATH in find_library which restrict libs finding path. (for dynamic dlls)

3. copy leak file from x86-windows-static to x86-windows installed folder.
```
LibeventTargets-static.cmake
LibeventTargets-static-debug.cmake
LibeventTargets-static-release.cmake
```
It is better if there was a out of box vcpkg support.

**Comment by azat** [comment] 2020-10-26 07:58
>It is better if there was a out of box vcpkg support.

On windows you cannot build [both](https://github.com/libevent/libevent/commit/90d80ef4167d97b11e01e80fcc4eaa447712e92f), but this can easily be fixed by the build system (vcpkg) I guess

**Comment by NancyLi1013** [comment] 2020-11-27 06:30
Hi @azat 

Thanks for looking into this and also for your suggestion.

But it seems that the problem is here:

```
# Find libraries
    macro(find_event_lib _comp)
        unset(_event_lib CACHE)
        find_library(_event_lib
                    NAMES "event_${_comp}"
                    PATHS "${_INSTALL_PREFIX}/lib"
                    NO_DEFAULT_PATH)
        if(_event_lib)
            list(APPEND LIBEVENT_LIBRARIES "libevent::${_comp}")
            set_case_insensitive_found(${_comp})
            message_if_needed(STATUS "Found libevent component: ${_event_lib}")
        else()
            no_component_msg(${_comp})
        endif()
    endmacro()
```
`NO_DEFAULT_PATH` should not be added here. I also tested this and found that there were no any libs found with this arguments `NO_DEFAULT_PATH`.

**Comment by azat** [comment] 2020-11-28 13:27
>NO_DEFAULT_PATH should not be added here. I also tested this and found that there were no any libs found with this arguments NO_DEFAULT_PATH.

Hm, but why `_INSTALL_PREFIX` is incorrect there?
@NancyLi1013 Can you print it out and see why it does not have lib/include?

**Comment by NancyLi1013** [comment] 2020-12-01 02:02
Sorry for the delay. I will try this today.

**Comment by azat** [comment] 2020-12-06 10:39
>Could you see something abnormal from the output?

If libraries located under that locations (I assume location is `F:/vcpkg/installed/x86-windows/lib:F:/vcpkg/installed/x86-windows/lib`) then no, can you verify this?

>Note: _INSTALL_PREFIX has been updated as get_filename_component(_INSTALL_PREFIX "${LIBEVENT_CMAKE_DIR}/../.." ABSOLUTE) instead of get_filename_component(_INSTALL_PREFIX "${LIBEVENT_CMAKE_DIR}/../../.." ABSOLUTE) in vcpkg.

Well this may break things, but you printed it and if it has libraries it should find them.

I remember that VS creates some subfolders for build type (i.e. `debug`) and similar, maybe this will help you?

**Closed** 2022-07-26 06:08 UTC
Labels: os:windows, build:cmake
