### ISSUE TITLE
win32 https server: all ssl connection failed after run some hours.

### ISSUE THREAD

**Issue by lastorder** [libevent/libevent#425] opened 2016-11-22 07:28 UTC
**I use libevent and openssl to start a https server, and I used SSL_CTX_set_verify to verify the client cert。
I start 8 event_base run in 8 thread.
usually after run some hours, the server is DoS.**

**in the abnormal logs, after verify the client cert, the 'event_callback_finalize_many_' is called before hand the request to the 'evhttp_set_gencb' callback fuction.
I found this problem in windows server 2008, and both 2.1.5 and 2.1.7 hava this problem.**

Below is  the log before and after the DoS.

 [16:05:15.507][T48592],[libevent2.1.7 0]    **evhttp_get_request_connection: new request from 127.0.0.1:60420 on 7120**
 [16:05:15.507][T48592],[libevent2.1.7 0]    Attempting connection to 127.0.0.1:60420
 [16:05:15.507][T48592],[libevent2.1.7 0]    event_add: event: 0C944DF8 (fd -1), EV_READ    call 0FDDB3B0]
 [16:05:15.507][T48592],[libevent2.1.7 0]    event_del: 0C944E38 (fd -1), callback 0FDDB3B0]
 [16:05:15.507][T48592],[libevent2.1.7 0]    event_del: 0C944DF8 (fd -1), callback 0FDDB3B0]
 [16:05:15.507][T48592],[libevent2.1.7 0]    event_del: 0C944E38 (fd -1), callback 0FDDB3B0]
 [16:05:15.507][T48592],[libevent2.1.7 0]    event_add: event: 0C944DF8 (fd 7120), EV_READ    call 0FDDB3B0]
 [16:05:15.507][T48592],[libevent2.1.7 0]    win32_add: adding event for 7120]
 [16:05:15.507][T48592],[libevent2.1.7 0]    event_add: event: 0C944DF8 (fd 7120), EV_READ   EV_TIMEOUT call 0FDDB3B0]
 [16:05:15.507][T48592],[libevent2.1.7 0]    event_add: event 0C944DF8, timeout in 1800 seconds 0 useconds, call 0FDDB3B0]
 [16:05:15.507][T48592],[libevent2.1.7 0]    event_del: 0C944E38 (fd 7120), callback 0FDDB3B0]
 [16:05:15.507][T48592],[libevent2.1.7 0]    event_add: event: 0C944DF8 (fd 7120), EV_READ   EV_TIMEOUT call 0FDDB3B0]
 [16:05:15.507][T48592],[libevent2.1.7 0]    event_add: event 0C944DF8, timeout in 1800 seconds 0 useconds, call 0FDDB3B0]
 [16:05:15.507][T48592],[libevent2.1.7 0]    timeout_next: event: 0C944DF8, in 1800 seconds, 0 useconds]
 [16:05:15.508][T48592],[libevent2.1.7 0]    win32_dispatch: select returned 1]
 [16:05:15.508][T48592],[libevent2.1.7 0]    event_active: 0C944DF8 (fd 7120), res 2, callback 0FDDB3B0]
 [16:05:15.508][T48592],[libevent2.1.7 0]    event_process_active: event: 0C944DF8, EV_READ   call 0FDDB3B0]
 [16:05:15.508][T48592],[libevent2.1.7 0]    event_add: event: 0C944DF8 (fd 7120), EV_READ   EV_TIMEOUT call 0FDDB3B0]
 [16:05:15.508][T48592],[libevent2.1.7 0]    event_add: event 0C944DF8, timeout in 375757 seconds 125000 useconds, call 0FDDB3B0]
 [16:05:15.508][T48592],[libevent2.1.7 0]    event_del: 0C944E38 (fd 7120), callback 0FDDB3B0]
 [16:05:15.508][T48592],[libevent2.1.7 0]    event_add: event: 0C944DF8 (fd 7120), EV_READ   EV_TIMEOUT call 0FDDB3B0]
 [16:05:15.508][T48592],[libevent2.1.7 0]    event_add: event 0C944DF8, timeout in 1800 seconds 0 useconds, call 0FDDB3B0]
 [16:05:15.508][T48592],[libevent2.1.7 0]    timeout_next: event: 0C944DF8, in 1800 seconds, 0 useconds]
 [16:05:15.510][T48592],[libevent2.1.7 0]    win32_dispatch: select returned 1]
 [16:05:15.510][T48592],[libevent2.1.7 0]    event_active: 0C944DF8 (fd 7120), res 2, callback 0FDDB3B0]
 [16:05:15.510][T48592],[libevent2.1.7 0]    event_process_active: event: 0C944DF8, EV_READ   call 0FDDB3B0]
 [16:05:15.510][T48592],[libevent2.1.7 0]    event_add: event: 0C944DF8 (fd 7120), EV_READ   EV_TIMEOUT call 0FDDB3B0]
 [16:05:15.510][T48592],[libevent2.1.7 0]    event_add: event 0C944DF8, timeout in 375757 seconds 125000 useconds, call 0FDDB3B0]
 **[16:05:15.510][T48592],[,[X509 cert common name:dongyu]
 [16:05:15.511][T48592],[,[X509 cert common name:client test]**
 [16:05:15.530][T48592],[libevent2.1.7 0]    event_del: 0C944E38 (fd 7120), callback 0FDDB3B0]
 [16:05:15.530][T48592],[libevent2.1.7 0]    event_add: event: 0C944DF8 (fd 7120), EV_READ   EV_TIMEOUT call 0FDDB3B0]
 [16:05:15.530][T48592],[libevent2.1.7 0]    event_add: event 0C944DF8, timeout in 1800 seconds 0 useconds, call 0FDDB3B0]
 [16:05:15.530][T48592],[libevent2.1.7 0]    timeout_next: event: 0C944DF8, in 1800 seconds, 0 useconds]
 [16:05:15.548][T48592],[libevent2.1.7 0]    win32_dispatch: select returned 1]
 [16:05:15.548][T48592],[libevent2.1.7 0]    event_active: 0C944DF8 (fd 7120), res 2, callback 0FDDB3B0]
 [16:05:15.548][T48592],[libevent2.1.7 0]    event_process_active: event: 0C944DF8, EV_READ   call 0FDDB3B0]
 [16:05:15.548][T48592],[libevent2.1.7 0]    event_add: event: 0C944DF8 (fd 7120), EV_READ   EV_TIMEOUT call 0FDDB3B0]
 [16:05:15.548][T48592],[libevent2.1.7 0]    event_add: event 0C944DF8, timeout in 375757 seconds 156000 useconds, call 0FDDB3B0]
 **[16:05:15.549][T48592],[libevent2.1.7 0]    event_del: 0C944DF8 (fd 7120), callback 0FDDB3B0]
 [16:05:15.549][T48592],[libevent2.1.7 0]    win32_del: Removing event for 7120]
 [16:05:15.549][T48592],[libevent2.1.7 0]    event_del: 0C944E38 (fd 7120), callback 0FDDB3B0]
 [16:05:15.549][T48592],[libevent2.1.7 0]    event_add: event: 0C944DF8 (fd 7120), EV_READ   EV_TIMEOUT call 0FDDB070]
 [16:05:15.549][T48592],[libevent2.1.7 0]    win32_add: adding event for 7120]
 [16:05:15.549][T48592],[libevent2.1.7 0]    event_add: event 0C944DF8, timeout in 1800 seconds 0** useconds, call 0FDDB070]
 [16:05:15.549][T48592],[libevent2.1.7 0]    event_add: event: 0C944DF8 (fd 7120), EV_READ   EV_TIMEOUT call 0FDDB070]
 [16:05:15.549][T48592],[libevent2.1.7 0]    event_add: event 0C944DF8, timeout in 1800 seconds 0 useconds, call 0FDDB070]
 [16:05:15.549][T48592],[libevent2.1.7 0]    timeout_next: event: 0C944DF8, in 1800 seconds, 0 useconds]
 [16:05:15.549][T48592],[libevent2.1.7 0]    win32_dispatch: select returned 1]
 [16:05:15.549][T48592],[libevent2.1.7 0]    event_active: 0C944DF8 (fd 7120), res 2, callback 0FDDB070]
 [16:05:15.549][T48592],[libevent2.1.7 0]    event_process_active: event: 0C944DF8, EV_READ   call 0FDDB070]
 [16:05:15.549][T48592],[libevent2.1.7 0]    event_add: event: 0C944DF8 (fd 7120), EV_READ   EV_TIMEOUT call 0FDDB070]
 [16:05:15.549][T48592],[libevent2.1.7 0]    event_add: event 0C944DF8, timeout in 375757 seconds 156000 useconds, call 0FDDB070]
 [16:05:15.549][T48592],[libevent2.1.7 0]    evhttp_add_header: key: Host val: 127.0.0.1:13497
 [16:05:15.549][T48592],[libevent2.1.7 0]    evhttp_add_header: key: Connection val: Keep-Alive
 [16:05:15.549][T48592],[libevent2.1.7 0]    evhttp_add_header: key: User-Agent val: Apache-HttpClient/4.5 (Java/1.8.0_101)
 [16:05:15.549][T48592],[libevent2.1.7 0]    evhttp_add_header: key: Accept-Encoding val: gzip,deflate
 [16:05:15.549][T48592],[libevent2.1.7 0]    evhttp_read_header: checking for post data on 7120
 **[16:05:15.549][T48592],[,[Got a (1) request for :/rest/netstar/fd/v1/detect/state?sor_id_list=%5B%227274595_5_9_20161121_160459_0_200_10_15%22%5D&_=1479714699119  upload data : ]**
 [16:05:15.549][T48592],[libevent2.1.7 0]    Query Param: sor_id_list -> ["7274595_5_9_20161121_160459_0_200_10_15"]
 [16:05:15.550][T48592],[libevent2.1.7 0]    Query Param: _ -> 1479714699119
 [16:05:15.550][T48592],[,[Server fuction start! url: /rest/netstar/fd/v1/detect/state]
 [16:05:15.551][T48592],[,[Server fuction end! ]
 [16:05:15.551][T48592],[libevent2.1.7 0]    evhttp_add_header: key: Content-Type val: application/json
 [16:05:15.551][T48592],[libevent2.1.7 0]    event_add: event: 0C944E38 (fd 7120),  EV_WRITE  EV_TIMEOUT call 0FDDB0B0]
 [16:05:15.551][T48592],[libevent2.1.7 0]    win32_add: adding event for 7120]
 [16:05:15.551][T48592],[libevent2.1.7 0]    event_add: event 0C944E38, timeout in 1800 seconds 0 useconds, call 0FDDB0B0]
 [16:05:15.551][T48592],[libevent2.1.7 0]    evhttp_add_header: key: Date val: Mon, 21 Nov 2016 08:05:15 GMT
 [16:05:15.551][T48592],[libevent2.1.7 0]    evhttp_add_header: key: Content-Length val: 89
 [16:05:15.551][T48592],[libevent2.1.7 0]    evhttp_write_buffer: preparing to write buffer
 [16:05:15.551][T48592],[libevent2.1.7 0]    event_add: event: 0C944E38 (fd 7120),  EV_WRITE  EV_TIMEOUT call 0FDDB0B0]
 [16:05:15.551][T48592],[libevent2.1.7 0]    event_add: event 0C944E38, timeout in 1800 seconds 0 useconds, call 0FDDB0B0]
 [16:05:15.551][T48592],[libevent2.1.7 0]    timeout_next: event: 0C944DF8, in 1800 seconds, 0 useconds]
 [16:05:15.551][T48592],[libevent2.1.7 0]    win32_dispatch: select returned 1]
 [16:05:15.551][T48592],[libevent2.1.7 0]    event_active: 0C944E38 (fd 7120), res 4, callback 0FDDB0B0]
 [16:05:15.551][T48592],[libevent2.1.7 0]    event_process_active: event: 0C944E38,  EV_WRITE  call 0FDDB0B0]
 [16:05:15.551][T48592],[libevent2.1.7 0]    event_add: event: 0C944E38 (fd 7120),  EV_WRITE  EV_TIMEOUT call 0FDDB0B0]
 [16:05:15.551][T48592],[libevent2.1.7 0]    event_add: event 0C944E38, timeout in 375757 seconds 156000 useconds, call 0FDDB0B0]
 [16:05:15.551][T48592],[libevent2.1.7 0]    event_del: 0C944E38 (fd 7120), callback 0FDDB0B0]
 [16:05:15.552][T48592],[libevent2.1.7 0]    win32_del: Removing event for 7120]
 [16:05:15.552][T48592],[libevent2.1.7 0]    event_add: event: 0C944DF8 (fd 7120), EV_READ   EV_TIMEOUT call 0FDDB070]
 [16:05:15.552][T48592],[libevent2.1.7 0]    event_add: event 0C944DF8, timeout in 1800 seconds 0 useconds, call 0FDDB070]
 [16:05:15.552][T48592],[libevent2.1.7 0]    event_del: 0C944E38 (fd 7120), callback 0FDDB0B0]
 [16:05:15.552][T48592],[libevent2.1.7 0]    timeout_next: event: 0C944DF8, in 1800 seconds, 0 useconds]
 [16:05:15.553][T48592],[libevent2.1.7 0]    win32_dispatch: select returned 1]
 [16:05:15.553][T48592],[libevent2.1.7 0]    event_active: 0C944DF8 (fd 7120), res 2, callback 0FDDB070]
 [16:05:15.553][T48592],[libevent2.1.7 0]    event_process_active: event: 0C944DF8, EV_READ   call 0FDDB070]
 [16:05:15.553][T48592],[libevent2.1.7 0]    event_add: event: 0C944DF8 (fd 7120), EV_READ   EV_TIMEOUT call 0FDDB070]
 [16:05:15.553][T48592],[libevent2.1.7 0]    event_add: event 0C944DF8, timeout in 375757 seconds 171000 useconds, call 0FDDB070]
 **[16:05:15.553][T48592],[libevent2.1.7 0]    event_del: 0C944DF8 (fd 7120), callback 0FDDB070]
 [16:05:15.553][T48592],[libevent2.1.7 0]    win32_del: Removing event for 7120]
 [16:05:15.553][T48592],[libevent2.1.7 0]    event_del: 0C944E38 (fd 7120), callback 0FDDB0B0]
 [16:05:15.553][T48592],[libevent2.1.7 0]    event_del: 0C944DF8 (fd 7120), callback 0FDDB070]
 [16:05:15.553][T48592],[libevent2.1.7 0]    event_del: 0C944E38 (fd 7120), callback 0FDDB0B0]
 [16:05:15.553][T48592],[libevent2.1.7 0]    event_del: 0C944DF8 (fd 7120), callback 0FDDB070]**
 [16:05:15.553][T48592],[libevent2.1.7 0]    event_del: 0C944E38 (fd 7120), callback 0FDDB0B0]
 [16:05:15.553][T48592],[libevent2.1.7 0]    event_del: 0C944DF8 (fd 7120), callback 0FDDB070]
 [16:05:15.553][T48592],[libevent2.1.7 0]    event_callback_finalize_many_: 3 events finalizing]
 [16:05:15.553][T48592],[libevent2.1.7 0]    event_del: 0C944DF8 (fd 7120), callback 0FDDB070]
 [16:05:15.553][T48592],[libevent2.1.7 0]    event_del: 0C944E38 (fd 7120), callback 0FDDB0B0]
 [16:05:15.553][T48592],[libevent2.1.7 0]    event_process_active: event: 0C944DF8, EV_READ   call 0FDD1120]
 [16:05:16.587][T48592],[libevent2.1.7 0]    win32_dispatch: select returned 1]
 [16:05:16.588][T48592],[libevent2.1.7 0]    event_active: 06CF58EC (fd 4944), res 2, callback 0FDDDD10]
 [16:05:16.588][T48592],[libevent2.1.7 0]    event_process_active: event: 06CF58EC, EV_READ   call 0FDDDD10]
 [16:05:16.698][T48592],[libevent2.1.7 0]    win32_dispatch: select returned 1]
 [16:05:16.698][T48592],[libevent2.1.7 0]    event_active: 06CF58EC (fd 4944), res 2, callback 0FDDDD10]
 [16:05:16.698][T48592],[libevent2.1.7 0]    event_process_active: event: 06CF58EC, EV_READ   call 0FDDDD10]
 [16:05:16.698][T48592],[libevent2.1.7 0]    **evhttp_get_request_connection: new request from 127.0.0.1:60424 on 7184**
 [16:05:16.698][T48592],[libevent2.1.7 0]    Attempting connection to 127.0.0.1:60424
 [16:05:16.698][T48592],[libevent2.1.7 0]    event_add: event: 0C83AE58 (fd -1), EV_READ    call 0FDDB3B0]
 [16:05:16.698][T48592],[libevent2.1.7 0]    event_del: 0C83AE98 (fd -1), callback 0FDDB3B0]
 [16:05:16.698][T48592],[libevent2.1.7 0]    event_del: 0C83AE58 (fd -1), callback 0FDDB3B0]
 [16:05:16.698][T48592],[libevent2.1.7 0]    event_del: 0C83AE98 (fd -1), callback 0FDDB3B0]
 [16:05:16.698][T48592],[libevent2.1.7 0]    event_add: event: 0C83AE58 (fd 7184), EV_READ    call 0FDDB3B0]
 [16:05:16.698][T48592],[libevent2.1.7 0]    win32_add: adding event for 7184]
 [16:05:16.698][T48592],[libevent2.1.7 0]    event_add: event: 0C83AE58 (fd 7184), EV_READ   EV_TIMEOUT call 0FDDB3B0]
 [16:05:16.698][T48592],[libevent2.1.7 0]    event_add: event 0C83AE58, timeout in 1800 seconds 0 useconds, call 0FDDB3B0]
 [16:05:16.698][T48592],[libevent2.1.7 0]    event_del: 0C83AE98 (fd 7184), callback 0FDDB3B0]
 [16:05:16.698][T48592],[libevent2.1.7 0]    event_add: event: 0C83AE58 (fd 7184), EV_READ   EV_TIMEOUT call 0FDDB3B0]
 [16:05:16.698][T48592],[libevent2.1.7 0]    event_add: event 0C83AE58, timeout in 1800 seconds 0 useconds, call 0FDDB3B0]
 [16:05:16.699][T48592],[libevent2.1.7 0]    timeout_next: event: 0C83AE58, in 1800 seconds, 0 useconds]
 [16:05:16.699][T48592],[libevent2.1.7 0]    win32_dispatch: select returned 1]
 [16:05:16.699][T48592],[libevent2.1.7 0]    event_active: 0C83AE58 (fd 7184), res 2, callback 0FDDB3B0]
 [16:05:16.699][T48592],[libevent2.1.7 0]    event_process_active: event: 0C83AE58, EV_READ   call 0FDDB3B0]
 [16:05:16.699][T48592],[libevent2.1.7 0]    event_add: event: 0C83AE58 (fd 7184), EV_READ   EV_TIMEOUT call 0FDDB3B0]
 [16:05:16.699][T48592],[libevent2.1.7 0]    event_add: event 0C83AE58, timeout in 375758 seconds 312000 useconds, call 0FDDB3B0]
 [16:05:16.700][T48592],[libevent2.1.7 0]    event_del: 0C83AE98 (fd 7184), callback 0FDDB3B0]
 [16:05:16.700][T48592],[libevent2.1.7 0]    event_add: event: 0C83AE58 (fd 7184), EV_READ   EV_TIMEOUT call 0FDDB3B0]
 [16:05:16.700][T48592],[libevent2.1.7 0]    event_add: event 0C83AE58, timeout in 1800 seconds 0 useconds, call 0FDDB3B0]
 [16:05:16.700][T48592],[libevent2.1.7 0]    timeout_next: event: 0C83AE58, in 1800 seconds, 0 useconds]
 [16:05:16.701][T48592],[libevent2.1.7 0]    win32_dispatch: select returned 1]
 [16:05:16.701][T48592],[libevent2.1.7 0]    event_active: 0C83AE58 (fd 7184), res 2, callback 0FDDB3B0]
 [16:05:16.701][T48592],[libevent2.1.7 0]    event_process_active: event: 0C83AE58, EV_READ   call 0FDDB3B0]
 [16:05:16.701][T48592],[libevent2.1.7 0]    event_add: event: 0C83AE58 (fd 7184), EV_READ   EV_TIMEOUT call 0FDDB3B0]
 [16:05:16.701][T48592],[libevent2.1.7 0]    event_add: event 0C83AE58, timeout in 375758 seconds 312000 useconds, call 0FDDB3B0]
 **[16:05:16.702][T48592],[,[X509 cert common name:dongyu]
 [16:05:16.703][T48592],[,[X509 cert common name:client test]**
 [16:05:16.726][T48592],[libevent2.1.7 0]    event_del: 0C83AE98 (fd 7184), callback 0FDDB3B0]
 [16:05:16.726][T48592],[libevent2.1.7 0]    event_add: event: 0C83AE58 (fd 7184), EV_READ   EV_TIMEOUT call 0FDDB3B0]
 [16:05:16.726][T48592],[libevent2.1.7 0]    event_add: event 0C83AE58, timeout in 1800 seconds 0 useconds, call 0FDDB3B0]
 [16:05:16.726][T48592],[libevent2.1.7 0]    timeout_next: event: 0C83AE58, in 1800 seconds, 0 useconds]
 [16:05:16.743][T48592],[libevent2.1.7 0]    win32_dispatch: select returned 1]
 [16:05:16.743][T48592],[libevent2.1.7 0]    event_active: 0C83AE58 (fd 7184), res 2, callback 0FDDB3B0]
 [16:05:16.743][T48592],[libevent2.1.7 0]    event_process_active: event: 0C83AE58, EV_READ   call 0FDDB3B0]
 [16:05:16.743][T48592],[libevent2.1.7 0]    event_add: event: 0C83AE58 (fd 7184), EV_READ   EV_TIMEOUT call 0FDDB3B0]
 [16:05:16.743][T48592],[libevent2.1.7 0]    event_add: event 0C83AE58, timeout in 375758 seconds 359000 useconds, call 0FDDB3B0]
 **[16:05:16.744][T48592],[libevent2.1.7 0]    event_del: 0C83AE58 (fd 7184), callback 0FDDB3B0]
 [16:05:16.744][T48592],[libevent2.1.7 0]    win32_del: Removing event for 7184]
 [16:05:16.744][T48592],[libevent2.1.7 0]    event_del: 0C83AE98 (fd 7184), callback 0FDDB3B0]
 [16:05:16.744][T48592],[libevent2.1.7 0]    event_del: 0C83AE58 (fd 7184), callback 0FDDB3B0]
 [16:05:16.744][T48592],[libevent2.1.7 0]    event_del: 0C83AE98 (fd 7184), callback 0FDDB3B0]
 [16:05:16.744][T48592],[libevent2.1.7 0]    event_del: 0C83AE58 (fd 7184), callback 0FDDB3B0]
 [16:05:16.744][T48592],[libevent2.1.7 0]    event_del: 0C83AE98 (fd 7184), callback 0FDDB3B0]
 [16:05:16.744][T48592],[libevent2.1.7 0]    event_callback_finalize_many_: 3 events finalizing]**
 [16:05:16.744][T48592],[libevent2.1.7 0]    event_del: 0C83AE58 (fd 7184), callback 0FDDB3B0]
 [16:05:16.744][T48592],[libevent2.1.7 0]    event_del: 0C83AE98 (fd 7184), callback 0FDDB3B0]
 [16:05:16.744][T48592],[libevent2.1.7 0]    event_process_active: event: 0C83AE58, EV_READ   call 0FDD1120]
 [16:05:28.501][T48592],[libevent2.1.7 0]    win32_dispatch: select returned 1]
 [16:05:28.501][T48592],[libevent2.1.7 0]    event_active: 06CF58EC (fd 4944), res 2, callback 0FDDDD10]
 [16:05:28.501][T48592],[libevent2.1.7 0]    event_process_active: event: 06CF58EC, EV_READ   call 0FDDDD10]
 [16:05:28.506][T48592],[libevent2.1.7 0]    win32_dispatch: select returned 1]
 [16:05:28.506][T48592],[libevent2.1.7 0]    event_active: 06CF58EC (fd 4944), res 2, callback 0FDDDD10]
 [16:05:28.506][T48592],[libevent2.1.7 0]    event_process_active: event: 06CF58EC, EV_READ   call 0FDDDD10]
 [16:16:20.289][T48592],[libevent2.1.7 0]    win32_dispatch: select returned 1]
 [16:16:20.290][T48592],[libevent2.1.7 0]    event_active: 06CF58EC (fd 4944), res 2, callback 0FDDDD10]
 [16:16:20.290][T48592],[libevent2.1.7 0]    event_process_active: event: 06CF58EC, EV_READ   call 0FDDDD10]
 [16:16:20.291][T48592],[libevent2.1.7 0]    win32_dispatch: select returned 1]
 [16:16:20.291][T48592],[libevent2.1.7 0]    event_active: 06CF58EC (fd 4944), res 2, callback 0FDDDD10]
 [16:16:20.291][T48592],[libevent2.1.7 0]    event_process_active: event: 06CF58EC, EV_READ   call 0FDDDD10]
 [16:16:20.292][T48592],[libevent2.1.7 0]    win32_dispatch: select returned 1]
 [16:16:20.292][T48592],[libevent2.1.7 0]    event_active: 06CF58EC (fd 4944), res 2, callback 0FDDDD10]
 [16:16:20.292][T48592],[libevent2.1.7 0]    event_process_active: event: 06CF58EC, EV_READ   call 0FDDDD10]
 [16:16:20.292][T48592],[libevent2.1.7 0]    evhttp_get_request_connection: new request from 127.0.0.1:65250 on 2660
 [16:16:20.292][T48592],[libevent2.1.7 0]    Attempting connection to 127.0.0.1:65250
 [16:16:20.293][T48592],[ libevent2.1.7 0]    event_add: event: 0ADA5F68 (fd -1), EV_READ    call 0FDDB3B0]
 [16:16:20.293][T48592],[ libevent2.1.7 0]    event_del: 0ADA5FA8 (fd -1), callback 0FDDB3B0]
 [16:16:20.293][T48592],[ libevent2.1.7 0]    event_del: 0ADA5F68 (fd -1), callback 0FDDB3B0]
 [16:16:20.293][T48592],[ libevent2.1.7 0]    event_del: 0ADA5FA8 (fd -1), callback 0FDDB3B0]
 [16:16:20.293][T48592],[ libevent2.1.7 0]    event_add: event: 0ADA5F68 (fd 2660), EV_READ    call 0FDDB3B0]
 [16:16:20.293][T48592],[ libevent2.1.7 0]    win32_add: adding event for 2660]
 [16:16:20.293][T48592],[ libevent2.1.7 0]    event_add: event: 0ADA5F68 (fd 2660), EV_READ   EV_TIMEOUT call 0FDDB3B0]
 [16:16:20.293][T48592],[ libevent2.1.7 0]    event_add: event 0ADA5F68, timeout in 1800 seconds 0 useconds, call 0FDDB3B0]
 [16:16:20.293][T48592],[ libevent2.1.7 0]    event_del: 0ADA5FA8 (fd 2660), callback 0FDDB3B0]
 [16:16:20.293][T48592],[ libevent2.1.7 0]    event_add: event: 0ADA5F68 (fd 2660), EV_READ   EV_TIMEOUT call 0FDDB3B0]
 [16:16:20.293][T48592],[ libevent2.1.7 0]    event_add: event 0ADA5F68, timeout in 1800 seconds 0 useconds, call 0FDDB3B0]
 [16:16:20.293][T48592],[ libevent2.1.7 0]    timeout_next: event: 0ADA5F68, in 1800 seconds, 0 useconds]
 [16:16:20.293][T48592],[ libevent2.1.7 0]    win32_dispatch: select returned 1]
 [16:16:20.293][T48592],[ libevent2.1.7 0]    event_active: 0ADA5F68 (fd 2660), res 2, callback 0FDDB3B0]
 [16:16:20.293][T48592],[ libevent2.1.7 0]    event_process_active: event: 0ADA5F68, EV_READ   call 0FDDB3B0]
 [16:16:20.293][T48592],[ libevent2.1.7 0]    event_add: event: 0ADA5F68 (fd 2660), EV_READ   EV_TIMEOUT call 0FDDB3B0]
 [16:16:20.293][T48592],[ libevent2.1.7 0]    event_add: event 0ADA5F68, timeout in 376424 seconds 484000 useconds, call 0FDDB3B0]
 [16:16:20.293][T48592],[ libevent2.1.7 0]    event_del: 0ADA5FA8 (fd 2660), callback 0FDDB3B0]
 [16:16:20.293][T48592],[ libevent2.1.7 0]    event_add: event: 0ADA5F68 (fd 2660), EV_READ   EV_TIMEOUT call 0FDDB3B0]
 [16:16:20.293][T48592],[ libevent2.1.7 0]    event_add: event 0ADA5F68, timeout in 1800 seconds 0 useconds, call 0FDDB3B0]
 [16:16:20.293][T48592],[ libevent2.1.7 0]    timeout_next: event: 0ADA5F68, in 1800 seconds, 0 useconds]
 [16:16:20.294][T48592],[ libevent2.1.7 0]    win32_dispatch: select returned 1]
 [16:16:20.294][T48592],[ libevent2.1.7 0]    event_active: 0ADA5F68 (fd 2660), res 2, callback 0FDDB3B0]
 [16:16:20.294][T48592],[ libevent2.1.7 0]    event_process_active: event: 0ADA5F68, EV_READ   call 0FDDB3B0]
 [16:16:20.294][T48592],[ libevent2.1.7 0]    event_add: event: 0ADA5F68 (fd 2660), EV_READ   EV_TIMEOUT call 0FDDB3B0]
 [16:16:20.294][T48592],[ libevent2.1.7 0]    event_add: event 0ADA5F68, timeout in 376424 seconds 484000 useconds, call 0FDDB3B0]
 [16:16:20.295][T48592],[],[X509 cert common name:dongyu]
 [16:16:20.296][T48592],[],[X509 cert common name:client test]

**Comment by lastorder** [comment] 2016-11-22 07:32
the log 'event_add: event 0C944DF8, timeout in 375757 seconds 125000 useconds, call 0FDDB3B0]' is abnomal .   But the DoS has noting to do with it.

what the num 375757 and 125000?


the time out num I set is 'timeout_next: event: 0C944DF8, in 1800 seconds, 0 useconds]'

**Comment by azat** [comment] 2016-11-24 08:53
Timers subtracted every time *poll/select/kqueue* calls, since some even can return earlier then your timer (because some fd is active).

**Comment by azat** [comment] 2016-11-24 08:56
Can you send (before DoS and after);
- `thread apply all bt` (in gdb)
- `lsof -np PID`

And plus it will be good to know what do you mean by DoS, after some period of time server doesn't answer anybody? maybe some deadlocks? Did you enable lock/thread-safe for libevent/bufferevents?

**Comment by lastorder** [comment] 2016-11-25 03:08
Thanks for your help!

after some period of time , all request is respond 'ssl cipher not match ' error. It respond very quickly, cannot be timeout. 

There is no deadlocks, after the DoS ,every request will go in 'SSL_CTX_set_verify' call back fuction, and print the log '[X509 cert common name:dongyu]'.   But not call the 'evhttp_set_gencb' call back.

I just enable lock/thread-safe in 'evhttp_set_gencb' call back fuction for find the specific url handler.  Is there any more lock needed?

**Comment by azat** [comment] 2016-11-25 08:04
You need two bits:
- `evthread_use_pthreads()`
- `BEV_OPT_THREADSAFE`

So if it respond with an error "ssl cipher not match", then why it should call your callback?

**Comment by lastorder** [comment] 2016-11-26 06:29
The problem is why it return 'ssl cipher not match' after run some hours?  I don't change anything.

**Comment by azat** [comment] 2016-11-26 15:43
Maybe some corruption? Can you provide a reproducer? Or/and run your program under:
- `vaglrind --tool=drd`
- `vaglrind --tool=memcheck`

**Comment by lastorder** [comment] 2016-11-28 07:39
I found this problem in windows.
Now I set BEV_OPT_THREADSAFE and evthread_use_windows_threads.
I need to test a long time to confirm whether effective.

Thanks.

**Comment by lastorder** [comment] 2016-11-30 03:50
The problem is still exist.

**Comment by azat** [comment] 2016-12-06 22:54
I'm not sure but if there are some re-connects then connections can fail, fixed in 86fa00706686d83bac627823543970fed27cf15b, so you can try compile latest libevent from sources and give it a try.

If this will not help, can you provide please some debug info from [this](https://github.com/libevent/libevent/issues/425#issuecomment-262722649) or [this (replace valgrind with some win32 tool)](https://github.com/libevent/libevent/issues/425#issuecomment-263070021).

**Comment by lastorder** [comment] 2016-12-07 08:47
thanks.  I will try.

**Comment by lastorder** [comment] 2016-12-12 02:02
I compile latest libevent and run two days, this problem doesn't occur.

**Comment by azat** [comment] 2016-12-12 05:24
Thanks! I will wait a little bit more and will close this issue after.

**Closed** 2017-05-01 20:21 UTC
Labels: os:win32
